- deployment/lib/buildspec/buildspec-feature.yml
- deployment/lib/buildspec/buildspec.yml
- deployment/lib/hassu-pipeline.ts
Parameter-store blokkiin ei sitten voinutkaan parametroida ympäristöä, joten ei sitten käytetä sitä.
> fix: optimoi buildia

- backend/src/database/projektiDatabase.ts
- backend/src/handler/projektiAdapter.ts
- backend/test/__snapshots__/apiHandler.test.ts.snap
- backend/test/database/__snapshots__/projektiDatabase.test.ts.snap
- graphql/inputs.graphql
- src/components/projekti/ProjektiLiittyvatSuunnitelmat.tsx
- src/components/projekti/ProjektiSideNavigation.tsx
- src/pages/yllapito/projekti/[oid]/index.tsx
Toistaiseksi käyttää projektin status kenttää mm. navigointipalkin kohteiden näyttämisessä, mutta ehdotukseni aiemmin oli, että jokaiselle vaiheelle (aloituskuulutus, suunniteluvaihe, nähtävilläolo jne) tulee vaihekohtainen tila/status (esim. AVOIN, AKTIIVINEN, LOPPUNUT, SULJETTU tms.). Näin saadaan hienojakoisempi vaiheistus/tila, jolle on tarvetta muutenkin, kuin vain navigoinnissa.
Samoin toistaiseksi perustietojen tallennuksen onnistumisilmoitus tulee ennen siirtymistä, ja siirtymä on viivästetty, mutta jatkossa ilmoitusten näyttäminen ulkoistetaan tuolta komponentilta ja ainakaan sen vuoksi ei tarvitse siirtymää viivästyttää, mutta mahdollisesti muista saavutettavuus tms syistä silloinkin?
> Feat: siirtyminen aloituskuulutukseen

- backend/integrationtest/projektiSearch/__snapshots__/projektiSearchService.test.ts.snap
- backend/integrationtest/projektiSearch/projektiSearchService.test.ts
- backend/src/aws/lambda.ts
- backend/src/database/projektiDatabase.ts
- backend/src/projektiSearch/dynamoDBStreamHandler.ts
- backend/src/projektiSearch/openSearchClient.ts
- backend/src/projektiSearch/projektiSearchMaintenanceService.ts
- backend/test/projektiSearch/dynamoDBStreamHandler.test.ts
- backend/test/setup.js
- deployment/lib/hassu-backend.ts
Käyttö: aws konsolista hassu-dynamodb-stream-handler-[env] lambdan testaustoiminnolla voi antaa seuraavat komennot:
Indeksin poisto:
```
{
"action": "deleteIndex"
}
```
Uudelleenindeksointi:
```
{
"action": "index"
}
```
> feature: hakuindeksin poisto-, sekä uudelleenindeksointitoiminto

- backend/src/handler/projektiAdapter.ts
- src/components/projekti/aloituskuulutus/IlmoituksenVastaanottajat.tsx
- src/components/projekti/suunnitteluvaihe/IlmoituksenVastaanottajat.tsx
- src/schemas/aloituskuulutus.ts
- src/schemas/vuorovaikutus.ts
Tähän on tehty myös BE-toteutus, jossa BE heittää hallitsemattoman virheen, jos viranomaisvastanottaja puuttuu. Huom! BE-muutos voi aiheuttaa ongemia, jos tietokannassa on jo projekteja, joilta puuttuu viranomaisvastaanottaja joko aloituskuulutuksesta tai vuorovaikutuksesta!! Sellainen projekti ei välttämättä enää päivity ollenkaan, ellei viranomaisvastaanottajaa laiteta.
> fix: viranomaisvastaanottajien olemassaolon validointi

- backend/src/handler/projektiAdapterJulkinen.ts
- graphql/types.graphql
- src/components/button/JataPalautettaNappi.tsx
- src/locales/fi/common.json
- src/locales/fi/projekti.json
- src/locales/sv/common.json
- src/locales/sv/projekti.json
- src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
- src/pages/suunnitelma/[oid]/suunnittelu.tsx
- src/services/api/fragmentTypes.json
sis. backendia ja APIa siltä osin, että pystyi testaamaan - backend tarvitsee jatkokehitystä esim julkisen nahtavillaolon lopulliset kentät, tuleeko snapshot malli, adapterin toiminta jne
> feat: nahtavillaolo kansalaisnakyma (HASSU-745)

- common/util/formatProperNoun.ts
* lookahead vaihdettu yksinkertaisempaan tapaan safarin tuen takia
> fix: safari-selaimen tuki

- src/components/projekti/hyvaksyminen/aineistot/Muokkausnakyma.tsx
- src/components/projekti/hyvaksyminen/kuulutuksenTiedot/KuulutuksessaEsitettavatYhteystiedot.tsx
- src/components/projekti/hyvaksyminen/kuulutuksenTiedot/KuulutusJaJulkaisuPaiva.tsx
- src/components/projekti/hyvaksyminen/kuulutuksenTiedot/Lukunakyma.tsx
- src/components/projekti/hyvaksyminen/kuulutuksenTiedot/MuutoksenHaku.tsx
- src/components/projekti/hyvaksyminen/kuulutuksenTiedot/PaatoksenPaiva.tsx
- src/components/projekti/hyvaksyminen/kuulutuksenTiedot/index.tsx
- src/locales/fi/common.json
- src/locales/sv/common.json
- src/schemas/hyvaksymispaatosKuulutus.tsx
Hox, puuttuu vielä pdf:ien napit, koska BE ei ole valmis, ja puuttuu hyväksymispäätöksen lisääminen ja sen katselu lukutilassa. Lisäksi yhteyshenkilöiden lukutilassa default-yhteyshenkilö eli projektipäällikkö ei näy. Tämä ongelma saattaa olla muissakin vaiheissa. Pitää miettiä yhtenäinen korjaus, esim. BE-ratkaisu.
> feat: hassu 855 hassu 804 hassu 823 hassu 813 hassu 810 hassu 803 hassu 805 hassu 818

- backend/src/database/dynamoDB.ts
- backend/src/database/projektiDatabase.ts
- deployment/bin/hassu.ts
- deployment/bin/setupEnvironment.ts
- deployment/lib/hassu-frontend.ts
- next.config.js
- src/pages/api/test/[oid]/nahtavillaolomenneisyyteen.dev.ts
polulla /api/test/[projektin oid]/nahtavillaolomenneisyyteen saa vaihdettua kuulutuksen nähtävilläolon vaihdettua päättymään 1.1.2022.
Onnistuin säätämään sen niin, että sitä ei bundlata mukaan prod-asennukseen.
> feat: toteuta testaukseen tapa siirtää nähtävilläolokuulutuksen päättymisaika välittömästi menneisyyteen

- backend/integrationtest/aloitusKuulutus/__snapshots__/aloitusKuulutusHandler.test.ts.snap
- backend/integrationtest/api/__snapshots__/api.test.ts.snap
- backend/integrationtest/api/apiTestFixture.ts
- backend/integrationtest/api/testUtil/hyvaksymisPaatosVaihe.ts
- backend/integrationtest/api/testUtil/tests.ts
- backend/src/asiakirja/suunnittelunAloitus/KutsuAdapter.ts
- backend/src/database/model/common.ts
- backend/src/database/model/projekti.ts
- backend/src/email/lahetekirje/LahetekirjeAdapter.ts
- backend/src/handler/asiakirjaAdapter.ts
- backend/src/projekti/adapter/adaptToAPI/adaptAloitusKuulutus.ts
- backend/src/projekti/adapter/adaptToDB/adaptAloitusKuulutusToSave.ts
- backend/src/projekti/adapter/adaptToDB/common.ts
- backend/src/projekti/adapter/common/lisaaTypename.ts
- backend/src/projekti/adapter/projektiAdapterJulkinen.ts
- backend/src/projekti/kayttoOikeudetManager.ts
- backend/src/util/vaylaUserToYhteystieto.ts
- backend/test/__snapshots__/apiHandler.test.ts.snap
- backend/test/asiakirja/__snapshots__/asiakirjaService.test.ts.snap
- backend/test/database/__snapshots__/projektiDatabase.test.ts.snap
- backend/test/fixture/projektiFixture.ts
- graphql/inputs.graphql
- graphql/types.graphql
- src/components/projekti/aloituskuulutus/KuulutuksenYhteystiedot.tsx
- src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
- src/services/api/fragmentTypes.json
Bäkkärin tallennus-adapteri ottaa huomioon uuden inputin. API-adapterit ottavat huomioon uudenlaisen tietorakenteen. Kun tehdään aloitusKuulutusJulkaisu, BE generoi yhteystiedot kuulutusYhteystiedoista ja kayttoOikeuksista. Projektipäällikkö otetaan aina mukaan. FE:n aloituskuulutus-lomake antaa uudenlaista inputia.
> Uusi tyypitys aloituskuulutuksen yhteystiedoille

- deployment/bin/setupEnvironment.ts
- next.config.js
Generoitu hostname tuli mukaan .env.local-tiedostosta, jota ei muualla kuin devaajan ympäristössä tarvita.
Oikea hostname tulee nyt täältä mistä alunperin pitikin: https://github.com/finnishtransportagency/hassu/blob/e1a74fb6be41ad9f38db6b4a8e82451a9265d9ef/deployment/lib/hassu-frontend.ts#L96
> fix: korjaa ilmoitustaulusyötteisiin oikea hostname

- deployment/localstack/docker-compose-m1.yml
- package.json
- src/components/kansalaisenEtusivu/Hakutulokset.tsx
- src/components/kansalaisenEtusivu/TyylitellytKomponentit.tsx
- src/locales/fi/projekti.json
- src/locales/sv/projekti.json
- src/pages/index.tsx
desktop- ja mobiilinäkymä toteutettu kansalaisen suunnitelmien listaukselle.
> feat: hassu 990 suunnitelmakortit

- backend/integrationtest/api/__snapshots__/api.test.ts.snap
- backend/integrationtest/api/api.test.ts
- backend/integrationtest/api/testUtil/tests.ts
- backend/src/aineisto/aineistoImporterClient.ts
- backend/src/aws/awsRequest.ts
- backend/src/aws/client.ts
- backend/src/aws/lambda.ts
- backend/src/database/projektiDatabase.ts
- backend/src/files/fileService.ts
- backend/src/handler/asiakirjaAdapter.ts
- backend/src/user/signedCookie.ts
- backend/test/__snapshots__/apiHandler.test.ts.snap
- backend/test/apiHandler.test.ts
- backend/test/aws/awsMock.ts
- backend/test/email/__snapshots__/emailHandler.test.ts.snap
- backend/test/email/emailHandler.test.ts
- backend/test/files/__snapshots__/fileService.test.ts.snap
- backend/test/files/fileService.test.ts
- backend/test/projekti/projektiAdapter.test.ts
- backend/test/user/userService.test.ts
- package-lock.json
- package.json
* poistettu kaikki suorat "aws-sdk"-importit backend-koodista
* vaihdettu aws-sdk:n mockaaminen erilaiseksi, koska vanha tyyli ei toiminut
* poistettu virheellinen importti aws-cdk:hon
* korjattu stubaus yksikkötesteissä; nyt ne eivät oikeasti koske localstackiin enää. Nyt myös stubausta käytetään "oikein" before/beforeEach/afterEach/after-funktioissa
> feat: optimoi AWS SDK-kutsut käyttämään kevyempää muotoa

- src/styles/globals.css
Nykyisellään bodyyn on lisätty _overflow-wrap: break-word_. Tämä toimii 99% tapauksista oikein. Jostain syystä flexboxeissa overflow käyttäytyy eritavoin joten tarvitsemme _overflow-wrap: anywhere_. Testailin ja koitin katsoa monessa paikassa toimiiko oikein. Mielestäni toimii.
Esimerkkiä -> https://dev.to/somshekhar/overflow-wrap-in-a-flex-container-35
> fix: Korjaa tekstien overflowaaminen flexboxeissa

- backend/src/projekti/adapter/adaptToAPI/adaptAloitusKuulutus.ts
- backend/src/projekti/adapter/adaptToAPI/adaptSuunnitteluVaihe.ts
- backend/src/projekti/adapter/adaptToDB/adaptVuorovaikutusToSave.ts
- backend/src/projekti/adapter/projektiAdapter.ts
- backend/src/projekti/adapter/projektiAdapterJulkinen.ts
- backend/src/projektiSearch/projektiSearchAdapter.ts
- backend/src/projektiSearch/projektiSearchService.ts
- backend/test/projektiSearch/projektiSearchService2.test.ts
Raportoitu bugi oli, että Vuorovaikutus-tagia ei näy kansalaispuolella silloin, kun pitäisi.
No, se johtui siitä, että indeksiin ei koskaan tullut sitä viimeinenTilaisuusPaattyy-arvoa.
Mikä johtui siitä, että indeksöiminen kaatui kesken Erroriin, koska oli jotain puuttuvia tietoja.
Joten nyt poistin sieltä niitä pakotuksia tietyille tiedoille, joita ei voi olla vielä siinä kohtaa kun indeksöinti tehdään.
MUTTA, edelleen indeksöinti kaatuu, jos projektilla ei ole velho-tiedoissa SEKÄ kuntaa ETTÄ maakuntaa. Eli testatessa sitten nämä hommat kuntoon hox pox.
Lisäksi korjasin bugin, joka vaati, että vuorovaikutuksella olisi muitakin yhteistietoja kuin se yksi pakollinen eli projari. Ts. Vuorovaikutuksen yhteystiedot (ne standardiyhteystiedot) voi olla undefined. (Sen sijaan …
> fix: hassu 1103 korjaa indeksoinnin logiikka ja poista estoja BE:stä indeksoinnin toimimiseksi

- backend/integrationtest/api/__snapshots__/api.test.ts.snap
- backend/integrationtest/api/__snapshots__/hyvaksymisPaatosHyvaksytty.test.ts.snap
- backend/integrationtest/api/records/HYVAKSYMISPAATOS_APPROVED.json
- backend/integrationtest/api/records/JATKOPAATOS_1_ALKU.json
- backend/integrationtest/api/records/NAHTAVILLAOLO.json
- backend/src/projekti/kayttoOikeudetManager.ts
- backend/test/__snapshots__/apiHandler.test.ts.snap
- backend/test/projekti/__snapshots__/kayttoOikeudetManager.test.ts.snap
- backend/test/projekti/__snapshots__/projektiHandler.test.ts.snap
- src/components/layout/ContentSpacer.tsx
- src/components/layout/HassuMuiThemeProvider.tsx
- src/components/layout/Section2.tsx
- src/components/projekti/KayttoOikeusHallinta.tsx
- src/components/projekti/ProjektiPageLayout.tsx
- src/pages/yllapito/perusta/[oid].tsx
- src/pages/yllapito/projekti/[oid]/henkilot.tsx
Muokattu backendia niin, että velhosta tulevalle varahenkilölle voidaan asettaa yleinenYhteystieto -tieto. Backendia muokattu myös niin, että projektipäällikkölle asetetaan aina _yleinenYhteystieto: true_.
Olen aiemmin rakentanut Section- ja SectionContent-komponentit vertikaaliseen välien luomiseen. Olen toteuttanut ne niin, että ne määrittelevät lapsikomponenttien välityksen suuruuden. KayttoOikeusHallinta-komponentissa tarvittiin customisoitua välitystä ja rakensin uudet versiot näistä kahdesta komponentista. Nimesin ne ContentSpacer- ja Section2-komponenteiksi. Halusin nimetä SectionContentin uudelleen, sillä tämän kaltaista vertikaalista välien asettamista tarvitaan muuallakin kuin Sectioneiden sisällä. En kuitenkaan halunnut tässä PR:ssä tehdä isoja refaktorointeja aiempiin …
> feat: Mahdollista julkisella puolella näytettävien projektin henkilöiden valinta

- backend/integrationtest/api/hyvaksymisPaatosHyvaksytty.test.ts
- backend/integrationtest/api/records/HYVAKSYMISPAATOS_APPROVED.json
- backend/integrationtest/api/records/JATKOPAATOS_1_ALKU.json
- backend/src/handler/tila/abstractHyvaksymisPaatosVaiheTilaManager.ts
- backend/src/projekti/status/projektiJulkinenStatusHandler.ts
- backend/src/projekti/status/projektiStatusHandler.ts
- backend/src/projekti/status/statusHandler.ts
- backend/src/util/dateUtil.ts
Tässä PR:ssä korjasin HASSU-1155 tiketissä havaitun hyväksymispäätösjulkaisun logiikkavirheen.
Osa julkaisuista tuli julkaisupäivän lopussa näkyville kansalais puolelle. Tämä johtui siitä, että backend/src/util/dateUtil.ts-tiedoston isDateTimeInThePast ja parseAndAddDateTime oli laitettu oletus kellon ajaksi 23.59. Muokkasin nyt sen parametrilla muokattavaksi. 
Muokkasin funktioiden käyttäytymistä niin, että parseAndAddDateTime ei aseta kellon aikaa erikseen mihinkään, joten se jää 00.00, mikäli sille annetaan YYYY-MM-DD -muodossa ISO-päivämäärä. Mikäli funktiolle annetaan "end-of-day" string-parametri, siirretään kellonaika päivän loppuun.
> fix: Korjaa logiikkaa milloin julkaisut tulevat näkyviin kansalaispuolelle

- backend/src/projektiSearch/projektiSearchAdapter.ts
- backend/src/projektiSearch/projektiSearchService.ts
- backend/test/projektiSearch/__snapshots__/dynamoDBStreamHandler.test.ts.snap
- backend/test/projektiSearch/__snapshots__/projektiSearchService.test.ts.snap
- backend/test/projektiSearch/projektiSearchService.test.ts
- graphql/inputs.graphql
- graphql/types.graphql
- src/locales/fi/projekti.json
- src/locales/sv/projekti.json
- src/pages/yllapito/index.tsx
Epäaktiivisia projekteja ei oteta mukaan julkisen puolen haussa. Virkamiespuolen haussa erotellaan epäaktiiviset ja epäaktiiviset toisistaan. BE palauttaa virkamiespuolen haun yhteydessä tiedon myös epäaktiivisten projektien määrästä. Haussa on mahdollista antaa boolean-parametri 'epaaktiivinen'. Testejä päivitetty.
UI:ssa epäaktiivisilla on oma täbinsä. Virkamiehen etusivukomponenttia on refaktoroitu toimivammaksi. Tieto siitä, mikä täbi on avattu, on yksinomaan queryparametreissa.
> feat: virkamiehen projektihaussa haetaan erikseen epäaktiiviset projektit (BE+FE)

- backend/src/projekti/adapter/adaptToDB/adaptSuunnitteluSopimusToSave.ts
- backend/src/projekti/adapter/projektiAdapter.ts
- backend/src/projekti/projektiValidator.ts
- backend/test/projekti/projektiAdapter.test.ts
- src/components/projekti/ProjektiSunnittelusopimusTiedot.tsx
fe+be+testit (ei cypress-testejä)
> feat: estä suunnittelusop. muuttaminen a.k.:n julk. jälkeen

- src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
Aiemmin hyväksymisdialogi jäi "open"-tilaan ja kun projekti vietiin hyväksyttäväksi, dialogi oli edelleen auki. Uudelleenkuulutus-sykliä toteuttamalla ongelman voi helpoiten havaita. Uudelleenkuuluta -> Tallenna ja lähetä Hyväksyttäväksi -> Hyväksy ja lähetä ->  Uudelleenkuuluta -> Tallenna ja lähetä Hyväksyttäväksi (ongelma havaittavissa)
> fix: Sulje dialogit oikein aloituskuulutussivulla, kun dialogista painetaan hyväksymispainiketta

- backend/integrationtest/api/__snapshots__/jatkopaatos.test.ts.snap
- backend/integrationtest/migraatio/__snapshots__/migration.test.ts.snap
- backend/src/projekti/adapter/adaptToAPI/adaptAloitusKuulutus.ts
- backend/src/projekti/adapter/adaptToAPI/adaptHyvaksymisPaatosVaihe.ts
- backend/src/projekti/adapter/adaptToAPI/adaptNahtavillaoloVaihe.ts
- backend/src/projekti/adapter/adaptToAPI/adaptVuorovaikutusKierros.ts
- backend/src/projekti/adapter/common/lisaaTypename.ts
- backend/src/projekti/adapter/projektiAdapter.ts
- backend/src/projekti/kayttoOikeudetManager.ts
- backend/src/projekti/projektiHandler.ts
- backend/test/projekti/kayttoOikeudetManager.test.ts
- backend/test/projekti/projektiAPIAdapter.test.ts
- backend/test/projekti/projektiAdapter.test.ts
- backend/test/projekti/projektiHandler.test.ts
- src/components/projekti/KayttoOikeusHallinta.tsx
- src/pages/yllapito/projekti/[oid]/henkilot.tsx
Toteutettu bäkkäriin ja fronttiin esto kunnan edustajan poistamiselle. Jos projektin henkilö on kunnan edustaja, sille ei pitäisi näkyä UI:ssa poistonappulaa. Lisäksi BE estää kunnan edustajan poistamisen.
Velho-synkronoinnin yhteydessä kunnan edustaja ei poistu, vaikka kunnan edustaja olisi ollut velhosta alun perin tullut projektin projektipäällikkö tai varahenkilö. Jos velhosta tulee synkronoinnin yhteydessä uusi projektipäällikkö tai varahenkilö, kunnan edustaja muutetaan tavalliseksi, muokattavissa olevaksi projektin henkilöksi synkronoinnin yhteydessä.
Kunnan edustaja on mahdollista vaihtaa, minkä jälkeen vanhan kunnan edustajan voi poistaa. Aloituskuulutuksessa, VuorovaikutusKierroksessa, NahtavillaoloVaiheessa, HyvaksymisPaatosVaiheessa ja JatkoPaatosVaiheissa voi olla tämän …
> feat: hassu 1161, kunnan edustajan poiston esto

- deployment/bin/hassu-waf.ts
- deployment/bin/maintenanceMode.ts
- deployment/lib/buildspec/buildspec-prod.yml
- deployment/lib/buildspec/buildspec-training.yml
- deployment/lib/buildspec/buildspec.yml
- deployment/lib/config.ts
- deployment/lib/hassu-frontend.ts
- deployment/lib/hassu-pipelines.ts
- deployment/lib/hassu-waf.ts
- deployment/package-lock.json
- deployment/package.json
- package-lock.json
- package.json
Toteutuksen idea:
* yksi WAF per account. Se asennetaan "npm run deploy:waf:dev"-komennolla
* WAF:ssa on yksi sääntö jokaista WAF:lla suojattavaa ympäristöä kohden. Säännöllä mätsätään host-headerin arvoon
* Jokaista sääntöä kohden on yksi regexp pattern set. Sen päivittäminen APIn kautta on nopeaa. Regex normaalisti ei osu host-headeriin, mutta jos halutaan kytkeä huoltokatko päälle, regex asetetaan mätsäämään kyseisen ympäristön host-headerin arvoon
* kytkentä päälle/pois tapahtuu "npm run maintenancemode set" ja "npm run maintenancemode clear"-komennoilla
* huoltokatkon aikana sivusto palauttaa http 503 statusta
* kytkennän jälkeen varmistetaan, että sivustolta tulee/ei tule 503 kuten pitää
> feat: asenna sovelluspalomuuri (AWS WAF) edustalle. Käytä WAF:ia huoltotaukojen kytkemiseen päälle/pois.

- src/locales/fi/suunnittelu.json
- src/locales/sv/suunnittelu.json
- src/pages/suunnitelma/[oid]/suunnittelu.tsx
Piilota palautteenantonappi kun nähtävilläolovaihe alkaa. Tätä varten piti vähän muokata käännöksiä, koska tekstissä oli linkki palautteenantoon.
> feat: Piilota suunnitteluvaiheen palautteenantonappi

- backend/integrationtest/aloitusKuulutus/__snapshots__/aloitusKuulutusUudelleenKuulutus.test.ts.snap
- backend/integrationtest/api/__snapshots__/api.test.ts.snap
- backend/integrationtest/api/__snapshots__/jatkopaatos.test.ts.snap
- backend/integrationtest/migraatio/__snapshots__/migration.test.ts.snap
- backend/src/projekti/adapter/projektiAdapterJulkinen.ts
- backend/test/__snapshots__/apiHandler.test.ts.snap
- graphql/types.graphql
- src/components/projekti/kansalaisnakyma/HyvaksymispaatosTiedot.tsx
- src/pages/suunnitelma/[oid]/aloituskuulutus.tsx
- src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
- src/pages/suunnitelma/[oid]/suunnittelu.tsx
- src/services/api/fragmentTypes.json
Hox! jos halutaan, että kansalaispuolelle ei välitetä esim. kuulutus muistutuksen antajille jne, niin sanokaa, niin teen erillisen tietotyypin HyvakysmisPaatosVaihePDFtJulkinen tms., jossa ei vaadita niitä muita pdf:iä kuin se yksi, mikä näytetään.
Tämä on nopeasti tehty toteutus, mutta pitäisi toimia.
> feat: hassu 1436 välitä kansalaispuolelle hyväksymispäätöksen kuulutus ja näytä se

- src/components/button/JataPalautettaNappi.tsx
- src/components/form/FormGroup.tsx
- src/components/form/HassuMuiSelect.tsx
- src/components/form/Select.tsx
- src/components/form/TextInput.tsx
- src/components/form/Textarea.tsx
- src/components/kansalaisenEtusivu/TyylitellytKomponentit.tsx
- src/components/layout/ScrollToTopButton.tsx
- src/components/layout/footer.tsx
- src/pages/tietoa-palvelusta/yhteystiedot-ja-palaute.tsx
- src/styles/globals.css
Korjaukset dokumentin Muistiinpanot_saavutettavuus.pdf perusteella
**Yleiset**
1. ok
2. ok - vanha versio
3. kts alla
4. nextjs placeholder sisällön liikkumisen estämiseksi latausten valmistuessa, ei ongelma ruudunlukijat osaavat huomioida tyhjät altit, minkä lisäksi elementillä on aria-hidden joka myöskin varmistaa ruudunlukijoiden toimvuuden
5. kts yllä
6. noscript elementit ovat logojen esittämisen tarkoitettuja nextjs:n automaattisesti luomia vaihtoehtoisia kuvien lataustapoja
7. - 
8. ok
9. kansalaisen murupolulla oma tiketti
10. ei toistettavissa, kielivalikkoon pääsee tabulaattorilla
**Etusivu**
1. ok
2. ok
3. oma tiketti
4. oma tiketti
5. korjattu painikkeiden piilotus, kun ensimmaisellä tai viimeisellä sivulla, vierekkäisiä linkkejä (sivunumerovalikko ja edellinen/seuraava) ei …
> feat: HASSU-1510 yleinen saavutettavuus (kansalaispuoli)

- src/components/projekti/kansalaisnakyma/ProjektiJulkinenStepper.tsx
* hoverilla harmaa boxshadow ja paksumpi underline stepeille, epaaktiivisten teksti primary font varilla
En tähän hätään keksinyt ratkaisua, miten meidän nykyisellä ratkaisulla saisi kaksi eri elementtiä aktivoitua hoveriksi (pallo + label), eli lähinnä miten saisi pallon hoverin päälle kun vain labelin päällä käydään.
> feat: HASSU-1373 stepperin saavutettavuus

- src/components/projekti/nahtavillaolo/kuulutuksentiedot/KuulutuksenTiedot.tsx
- src/components/projekti/paatos/kuulutuksenTiedot/index.tsx
- src/components/projekti/suunnitteluvaihe/LuonnoksetJaAineistot/MuokkaustilainenLomake.tsx
- src/components/projekti/suunnitteluvaihe/Perustiedot/SuunnittelunEteneminenJaArvioKestosta.tsx
- src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/index.tsx
- src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/index.tsx
- src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
- src/schemas/suunnittelunPerustiedot.ts
- src/util/defaultEsitettavatYhteystiedot.ts
Johtui siitä, että lomakkeiden oletusarvoihin valui ylimääräinen kenttiä (elyOrganisaatio).
Lisäksi muokkasin kutsussa olevien monikielisten kenttien validointeja ja triggeröintiä sellaiseksi, että erroria näytetään, jos tieto on toisella kielellä. Virheilmoitus poistuu näkyvistä kun tieto on täytetty molemmilla kielillä.
> fix: Kuulutuksia ei pääse julkaisemaan, jos kuulutukselle lisätty projektihenkilöiden ulkopuolisia yhteystietoja

- src/components/layout/footer.tsx
Katsoin väylä.fi -sivuston sosiaalisen median ikoneja ja linkkejä. Siellä myös title annettu a-elementille ja lapsielementti-ikonissa ei ole mitään aria-attribuutteja. Meillä sinne tulee sentään aria-hidden="true", mikä ilmaisee, että kyseessä on vain decoratiivinen kuva, jolle ei tarvitse antaa muita aria-attributteja. 
Testattu myös toimivaksi Macin VoiceOver ruudunlukijalla.
> fix: Korjaa varoitukset footerin sosiaalisen median linkeistä

- src/pages/suunnitelma/[oid]/suunnittelu.tsx
…kansalaispuolella. Ennen meni pötköön. Esittelyaineistot taas meni allekkain, mutta liikaa väliä niiden välissä.
> feat: HASSU-1593 Korjaa se, miten suunnitelmaluonnokset näytetään

- backend/src/aineisto/PartiallyMandatory.ts
- backend/src/aineisto/PartiallyRequiredAndNonNullable.ts
- backend/src/velho/velhoClient.ts
Käytä backupina versiot-arrayn vikaa objektia, ja sen jälkeen päätason objektin tietoja
> fix: Älä oleta että tuorein-versio -avain on olemassa

- src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/index.tsx
Kun vuorovaikutustilaisuuksien lisäämisnapit ovat aktiivisia, niissä tulisi olla sininen ääriviiva ja siniset ikonit (ks. tiketissä oleva kuva). Kun tietyntyyppistä vuorovaikutusta on lisätty, nappulasta tulee solidi sininen. Jos nappulat ovat epäaktiivisia (vuorovaikutus julkaistu), ne ovat hailakoita.
Tein lisäksi pienen varjoefektin, jos kursorin vie aktiivisen nappulan päälle. Jos kursorin vie aktiivisen ääriviivallisen nappulan päälle, sen valkoinen sisus muuttuu hieman sinertäväksi. Lisäsin paddingiä vasemalla ja oikealla, niin tulee enemmän sketch-kuvien näköinen nappula. Kaikki vaaleat sävyt eivät ole tarkoituksella ihan valkoisia, koska sketch-kuvissakaan ei ollut.
> fix: Vuorovaikutustilaisuusdialogin nappuloitten värit ja muut ulkoasu kuntoon

- under-maintenance/pages/_app.tsx
Ilman muutosta näyttää tältä:
Muutoksen kanssa tältä:
Korjausta voi testata itsekin ajamalla
npm run export-under-maintenance
npm run deploy:frontend
ja menemällä kattomaan cloudfrontissa olevasta frontista /huoltokatko.index.html
> fix: Korjaa huoltokatkosivulla näytettävät ikonit

- backend/src/handler/tila/aloitusKuulutusTilaManager.ts
- backend/src/projekti/validator/projektiValidator.ts
- backend/test/handler/tila/aloitusKuulutusTilaManager.test.ts
- backend/test/projekti/validator/projektiValidator.test.ts
- src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
Huomioitu myös, että jos uudelleenkuulutus on palautettu, pitäisi voida muokata vähäisen menettelyn totuusarvoa.
> fix: hassu-1775 vähäisen menettelyn projektin aloituskuulutuksen voi uudelleenkuuluttaa

- backend/src/handler/tila/KuulutusTilaManager.ts
- backend/test/fixture/projektiFixture.ts
- backend/test/handler/tila/nahtavillaoloTilaManagerUudelleenkuuluta.test.ts
Tässä PR:ssä tehdyt ominaisuudet:
* Jos avaa uudelleenkuulutuksen ja vanha kuulutus ei ole vielä tullut julkiseksi, sen julkiseksi tuleminen perutaan.
* Kuitenkin jos jokin kuulutus/uudelleenkuulutus on tullut julkiseksi kansalaiselle, sitä ei koskaan piiloteta.
* Jos hyväksytään uudelleenkuulutus, joka tulee heti julki, aiemmin julki oleva kuulutus laitetaan piiloon. (Tämä oli toteutettu jo aiemmin.)
* BE-testit näihin liittyen.
On tarkoitus, että virkamies laittaa "käsin" sähköpostin kunnille/viranomaisille, kun uudelleenkuulutus avataan, että "hei, älkää muuten julkaiskokaan sitä aiempaa kuulutusta". Tämän vuoksi s.postin lähetyshommiin ei ole mitään muutosta tässä. Automaattinen s.postiviesti kyseisessä tilanteessa on jatkokehitystiketti (ei luotu vielä).
> feat: Hassu 1292 uudelleenkuulutus peruu vanhan julkaisun

- backend/integrationtest/api/testUtil/util.ts
- backend/integrationtest/migraatio/migration.test.ts
- backend/src/projekti/adapter/projektiAdapterJulkinen.ts
- backend/src/projekti/projektiHandlerJulkinen.ts
- backend/test/__snapshots__/apiHandler.test.ts.snap
- src/components/kansalainen/EiJulkaistuSivu.tsx
- src/locales/fi/projekti.json
- src/locales/sv/projekti.json
- src/pages/suunnitelma/[oid]/[...all].tsx
- src/pages/suunnitelma/[oid]/aloituskuulutus.tsx
- src/pages/suunnitelma/[oid]/hyvaksymismenettelyssa.tsx
- src/pages/suunnitelma/[oid]/hyvaksymispaatos.tsx
- src/pages/suunnitelma/[oid]/index.tsx
- src/pages/suunnitelma/[oid]/jatkopaatos1.tsx
- src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
- src/pages/suunnitelma/[oid]/suunnittelu.tsx
Tiketin haluttu toiminnallisuus oli, että jos kunnan virkamies (tai joku muu vastaava kansalaistaho) saa jotenkin käsiinsä linkin projektin julkisen puolen sivulle, hän näkee siellä ilmoituksen, että projektin sivua ei ole vielä julkaistu, sen sijaan että näkisi virheviestin. Tällainen tilanne voi sattua, jos projekti on julkaistu, ja pdf:ään on generoitu linkki projektin julkiselle sivulle. Henkilöt, joille kuulutus lähtee s.postilla, pääsevät käsiksi linkkiin ennen kuin sivu on julkinen.
Tilanne voi sattua kaikissa projektin vaiheissa, koska migroitujen projektien tapauksessa projekti tulee näkyville julkiselle puolelle vasta kun ensimmäinen kuulutus/kutsu on julki Hassussa. Toisin sanottuna kaikille julkisen projektin alasivuilla tulee näkyä tilanteen vaatiessa tieto siitä, että …
> feat: hassuyp 68 ei-julkisen projektin kansalaisnäkymä

- backend/src/projekti/adapter/adaptToAPI/adaptAloitusKuulutus.ts
- backend/src/projekti/adapter/adaptToAPI/adaptHyvaksymisPaatosVaihe.ts
- backend/src/projekti/adapter/adaptToAPI/adaptNahtavillaoloVaihe.ts
- backend/src/projekti/validator/projektiValidator.ts
- backend/test/projekti/validator/projektiValidator/euRahoitus.test.ts
- backend/test/projekti/validator/projektiValidator/kielitiedot.test.ts
- backend/test/projekti/validator/projektiValidator/suunnitteluSopimus.test.ts
- backend/test/projekti/validator/projektiValidator/suunnitteluSopimus.ts
- common/util/operationValidators.ts
En ole tästä logiikasta hirveän ylpeä. Vähän monimutkaiseksi jäi. Olen parannusehdotuksille avoin.
> fix: HASSUYP-157 Korjaa Suunnittelusopimustiedon (ja muiden lukituksen alaisten tietojen) muuttamisvalidointilogiikkaa

- backend/src/testing/dateMoverTool.ts
- backend/test/testing/dateMoverTool.test.ts
- cypress/e2e/2-perusta-projekti/008-nahtavillaolovaihe-perustiedot.cy.ts
- cypress/e2e/4-migraatio/1-migraatio.cy.ts
- cypress/support/nahtavillaolo.ts
- cypress/support/util.ts
- src/components/projekti/AineistoSivunPainikkeet.tsx
- src/components/projekti/Ajansiirto.tsx
- src/components/projekti/common/KansalaisenAineistoNakyma.tsx
- src/components/projekti/lukutila/AineistoMuokkausSection.tsx
- src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/Lukunakyma.tsx
- src/components/table/HassuTable.tsx
Ohessa pari pienempää muutosta:
- dayjs plugin customParseFormat aiheutti sen, että dayjs antoi validileimaa liian laveasti. Sen vuoksi lisäsin dateMoverTooliin erillisen validoinnin, jossa ei ole käytössä customParseFormattia.
- Lisäksi lisätty myös lisäaineistoihin UUSI-merkinnät. (aiemmin oli vain nähtäville asetettavassa aineistossa)
> chore: HASSU-1824 Aineistomuokkauksen automaattitestien lisäys

- backend/src/projektiSearch/projektiSearchService.ts
* poista meidän pilkkomista hakutermeistä välimerkit ym koska:
"Standard analyzer – Parses strings into terms at word boundaries according to the Unicode text segmentation algorithm. It removes most, but not all, punctuation and converts strings to lowercase. You can remove stop words if you enable that option, but it does not remove stop words by default."
> feat: HASSUYP-238 haun korjaus

- backend/src/projekti/adapter/projektiAdapter.ts
- backend/test/__snapshots__/apiHandler.test.ts.snap
- graphql/types.graphql
- src/components/projekti/common/StyledMap.tsx
- src/pages/yllapito/projekti/[oid]/kiinteistonomistajat.dev.tsx
Tulin tajunneeksi, että jos kun projektille ensimmäistä kertaa lisätään karttarajaus.geojson, pitää projektin tiedot hakea uudelleen, että karttarajaustiedosto haetaan kun dialogi avataan uudemman kerran. Jotta dialogi toimii riippumatta siitä onko projektin tietoja haettu uudelleen, muokkasin toteutusta niin, ettei projektin tiedoista tarkisteta onko karttarajausta vaiko ei.
> fix: Korjaa tilanne, jossa geojson lisätään ensimmäistä kertaa

- backend/src/handler/asiakirjaHandler.ts
- backend/src/handler/tila/KuulutusTilaManager.ts
- backend/src/ilmoitustauluSyote/ilmoitustauluSyoteAdapter.ts
- backend/src/ilmoitustauluSyote/ilmoitustauluSyoteService.ts
- backend/src/projekti/status/projektiJulkinenStatusHandler.ts
- common/links.ts
- src/components/projekti/lukutila/HenkilotLukutila.tsx
- src/components/projekti/paatos/aineistot/MuokkausNakyma/TiedostoLomake/HyvaksymisPaatosTiedostotTaulu.tsx
- src/components/projekti/paatos/aineistot/MuokkausNakyma/TiedostoLomake/MuokkaustilainenPaatosTiedostot.tsx
- src/components/projekti/paatos/aineistot/MuokkausNakyma/TiedostoLomake/index.tsx
- src/locales/fi/projekti.json
- src/locales/sv/projekti.json
Jatkopäätöksien käsittelyissä oli selkeitä puutteita. 
- Syöteindeksiin ei mennyt 1. tai 2. jatkopäätöksistä dokumentteja.
-  `2. jatkopäätökseen migroidut projektit ei saanut oikeita statuksia kun 2. kuulutus julkaistiin. Seurauksena oli se, ettei projektia/suunnitelmaa ikinä näkynyt julkisella puolella
Lisäksi korjattu
- Lisätty ääkköstystä Henkilöt -sivulle
- Korjattu muokkaustilaisilla sivuilla olevien päätöstiedostojen tilan näyttäminen
- Lisätty puuttuvia parametreja asiakirjaHandlerista
> fix: HASSUYP-343 Korjaa jatkopäätöksien julkaisujen käsittelyä

- src/components/HyvaksymisEsitys/HyvaksymisEsitysLomake.tsx
- src/components/HyvaksymisEsitys/HyvaksymisEsitysLukutila.tsx
- src/components/HyvaksymisEsitys/MuuTekninenAineisto.tsx
- src/components/HyvaksymisEsitys/getDefaultValuesForForm.ts
- src/hooks/useHandleUploadedFiles.ts
- src/hooks/useHyvaksymisEsitys.ts
- src/hooks/useSpinnerAndSuccessMessage.ts
- src/pages/yllapito/projekti/[oid]/hyvaksymisesitys.tsx
Hahmottelua sille, miten hyväksymisesityksen FE-puolen jäsentelisi. Toteutettu toimiva lomake, jossa on tosin mukana vasta vain yksi datapiste (muu aineisto koneelta on mahdollista lisätä).
> feat: hassuyp 397 hyv es fe runko

- backend/integrationtest/HyvaksymisEsitys/adaptHyvaksymisEsitysToAPI.test.ts
- backend/integrationtest/HyvaksymisEsitys/haeTiedot.test.ts
- backend/src/HyvaksymisEsitys/actions/haeTiedot.ts
- backend/src/HyvaksymisEsitys/actions/tallennaJaLahetaHyvaksyttavaksi.ts
- backend/src/HyvaksymisEsitys/adaptToApi/adaptHyvaksymisEsitysToAPI.ts
- backend/src/HyvaksymisEsitys/s3Calls/persistFile.ts
- src/components/HyvaksymisEsitys/Dialogs/HyvaksyDialog.tsx
- src/components/HyvaksymisEsitys/Dialogs/PalautaDialog.tsx
- src/components/HyvaksymisEsitys/HyvaksymisEsitysLomake.tsx
- src/components/HyvaksymisEsitys/HyvaksymisEsitysLukutila.tsx
- src/components/HyvaksymisEsitys/LomakeComponents/HyvaksyTaiPalautaPainikkeet.tsx
- src/components/HyvaksymisEsitys/LomakeComponents/KuulutuksetJaKutsu.tsx
- src/components/HyvaksymisEsitys/LomakeComponents/MaanomistajaLuettelo.tsx
- src/pages/yllapito/projekti/[oid]/hyvaksymisesitys.tsx
Toteutettu "lähetä hyväksyttäväksi", "hyväksy", "palauta" ja "muokkaa" napit + dialogit, eli kaikki mikä liityy hyväksymisesityksen tilasiirtymiin. Mikä nappi näkyy kellekin ja milloin pitäisi olla kunnossa. Napit toimivat. Nappien ulkonäön ei ole tarkoitus olla vielä lopullinen. Koodin jäsentelyn ja nappien toimivuuden on tarkoitus olla kunnossa. Dialogien pitäisi olla speksin mukaisia (sisältö ja miten ne käyttäytyvät, ulkonäkö ei välttämättä).
Koodia jäsennelty. Korjattu yksi BE-logiikkavirhe ja tehty sille pienet testit.
Testaamisessa huomioitavaa:
Ei ole mahdollista lähettää hyväksyttäväksi projektia, jolla ei ole suunnitelmaa. Suunnitelmaa ei voi kuitenkaan vielä UI:n kautta lisätä. Lisää "muu aineisto velhosta" ja aws:ssä käy kopioimassa aineistotieto suunnitelmatiedoksi.
Ei ole …
> feat: hassuyp 404 hyv es tilasiirtymat

- deployment/lib/buildspec/buildspec-dev.yml
- deployment/lib/buildspec/buildspec-prod.yml
- deployment/lib/buildspec/buildspec-test.yml
- deployment/lib/buildspec/buildspec-training.yml
Tulee timeout jos omistajia paljon. Luotetaan että indeksi pysyy ajan tasalla stream eventtien välityksellä. Jos päivitetään asetuksia ja mappauksia pitää muistaa deletoida ja indeksoida indeksit uudestaan.
> fix: Poistetaan automaattinen omistajien ja muistuttajien indeksointi

- src/pages/api/slo.ts
Tuotannossa ohjaa logoutin aina https://vayliensuunnittelu.fi osoitteeseen vaikka KeycloakDomain on www.vayliensuunnittelu.fi. Koodissa ei sinänsä mitään vikaa, vaan pakko sen OnPrem proxyn muuttaa se Location header. Tähän auttaa se että muutetaan FRONTEND_DOMAIN_NAME tuotannossa käyttämään www.vayliensuunnittelu.fi arvoa.
> fix: Korjaa tuotannon sso logout

- src/components/HyvaksymisEsitys/HyvaksymisEsitysLomake.tsx
- src/components/HyvaksymisEsitys/HyvaksymisEsitysLukutila.tsx
Toteutettu sulje muokkaus -nappi. Lisätty leaveConfirm hyväksymisesityksen lomakesivulle. Laitettu custom "leave confirm" myös muokkauksen sulkemistoimintoon. Huom! Sketch-kuvista poiketen muokkauksen sulkunapin teksti on "Sulje muokkaus" eikä "Palaa tallentamatta". Tämä on tahallista.
Huom! Muokkaustilan sulkeminen onnistuu vain, jos hyväksymisesitykselle merkityt kaikki tiedostot ovat oikeasti olemassa (eikä esim. feikattu).
> feat: hassuyp 404 muokkauksen sulku

- src/components/KuntatietoMissingNotification.tsx
- src/components/projekti/HyvaksyJaPalautaPainikkeet.tsx
- src/components/projekti/ProjektiPageLayout.tsx
- src/components/projekti/TallennaLuonnosJaVieHyvaksyttavaksiPainikkeet.tsx
- src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/Lukunakyma.tsx
- src/components/projekti/paatos/aineistot/Lukunakyma.tsx
- src/components/projekti/perusosio/ProjektinLinkit.tsx
- src/components/projekti/suunnitteluvaihe/EpaaktiivinenTilaVuorovaikutukselle/index.tsx
- src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/index.tsx
- src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
- src/pages/yllapito/projekti/[oid]/kasittelyntila.tsx
- src/util/velhoUtils.ts
Tiketti: [HASSUYP-347](https://extranet.vayla.fi/jira/browse/HASSUYP-347)
Huom: Lisätty util-funktio projektivelho urlin muodostamiseksi
> Fix: HASSUYP-347 Kuulutuksen ja kutsun lähettäminen/hyväksyntä vaativat velhon kunnan ja maakunnan. 

- backend/src/projekti/status/getProjektiStatus.ts
- backend/test/projekti/status/getProjektiStatus.test.ts
Virheellisesti projektin statusarviossa tarkasteltiin, onko hyväksymisvaihe/jatkopaatos1/2vaiheJULKAISUN aineistot kunnossa - sen sijaan etä olisi tarkasteltu VAIHETTA. Lisäksi aineiston ok-tarkistuksessa oltiin unohdettu tarkastaa, onko hyväksymispäätös-tiedosto kunnossa. Nyt tämä on korjattu, ja testejä on päivitetty ja lisätty.
> feat: hassuyp 433 status fix

- src/components/HyvaksymisEsitys/LomakeComponents/TiedostoInputNewTable.tsx
- src/components/projekti/common/AineistojenValitseminenDialog.tsx
- src/components/projekti/common/Aineistot/AineistoNewTable/AineistoTable.tsx
- src/components/projekti/common/Aineistot/AineistoTable/AineistoTable.tsx
- src/components/projekti/lausuntopyynnot/LausuntoPyynnonTaydennysForm/Muistutukset/Table.tsx
- src/components/projekti/lausuntopyynnot/LausuntoPyynnonTaydennysForm/MuuAineisto/Table.tsx
- src/components/projekti/lausuntopyynnot/LausuntoPyyntoForm/LisaAineistot/Table.tsx
- src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/Lukunakyma.tsx
- src/components/projekti/paatos/aineistot/Lukunakyma.tsx
- src/components/projekti/paatos/aineistot/MuokkausNakyma/TiedostoLomake/HyvaksymisPaatosTiedostotTaulu.tsx
- src/components/projekti/suunnitteluvaihe/komponentit/AineistoTable.tsx
- src/components/table/HassuTable.tsx
Projektissa VLS-TESTI Peten projekti 2 on valmiiksi aineistoja vajaa 900. Ei niitä tosin noin montaa voi valita, kun dynamodb:ssä tila loppuu kesken viimeistään siinä vaiheessa kun yrittää hyväksyä.
> fix: HASSUYP-332: Otetaan virtualisointi pois käytöstä
