finnishtransportagency/hassu

src/components/button/Button.tsx
src/components/projektiListaus.tsx
src/pages/yllapito/index.tsx

Korjattu etusivun projektilistausta ja päivitetty sivun tyylejä.

feature: korjaa etusivun projektilistauksen linkit

---

deployment/lib/config.ts
deployment/lib/hassu-backend.ts
deployment/lib/hassu-pipeline.ts

Testasin omalla ympäristölläni että toimii.

feature: lisää ympäristömuuttuja VELHO_ENVIRONMENT, jolla voidaan dev/test kytkeä prod velhoon

---

src/components/form/DatePicker.tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
src/pages/yllapito/projekti/[oid]/index.tsx
src/styles/form/FormGroup.module.css

Käyttää (ainakin) toistaiseksi input elementtiä.

feat: Lisää kuulutuspäiväkenttä aloituskuulutussivulle

---

src/components/ExtLink.tsx
src/components/projekti/KayttoOikeusHallinta.tsx
src/components/projekti/ProjektiErrorNotification.tsx
src/components/projekti/ProjektiKuntatiedot.tsx
src/components/projekti/ProjektiPageLayout.tsx
src/components/projekti/ProjektiPerustiedot.tsx
src/components/projekti/ProjektiSideNavigation.tsx
src/pages/yllapito/perusta/[oid].tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
src/pages/yllapito/projekti/[oid]/henkilot.tsx
src/pages/yllapito/projekti/[oid]/index.tsx
src/schemas/projekti.ts

Henkilöiden hallintalomakkeen lisäksi loin projektin validointia varten skeeman projekti.ts:ään, johon voidaan lisätä sivuilla halutut tarkistukset.

feature: Lisää henkilösivulle henkilöiden hallintalomake

---

backend/bin/createVelhoProjekti.ts
backend/bin/deleteVelhoProjekti.ts
backend/bin/templates/tieProjekti.ts
backend/src/velho/velhoClient.ts
package.json

Käyttö:
npm run createVelhoProjekti -- --templateName tieProjekti
npm run deleteVelhoProjekti -- --oid 1.2.246.578.5.1.123123123

feat: komentorivityökalu Velho-projektien luomiseen ja poistamiseen

---

src/__tests__/__snapshots__/Perusta.test.tsx.snap
src/components/button/Button.tsx
src/components/button/IconButton.tsx
src/components/layout/header/virkamiesHeader.tsx
src/components/projekti/ProjektiPageLayout.tsx
src/components/projekti/ProjektiSideNavigation.tsx
src/hooks/useCurrentUser.tsx
src/hooks/useProjekti.tsx
src/pages/_app.tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
src/pages/yllapito/projekti/[oid]/henkilot.tsx
src/pages/yllapito/projekti/[oid]/index.tsx

Muokkasin SWR-configia niin, että onFocus revalidointeja ei enää tapahdu. Kutsut backendiin vähenee.

feat: Disabloi lomakekentät muokkausoikeudettomalta käyttäjältä

---

backend/src/config.ts
backend/src/email/email.ts
backend/src/handler/projektiHandler.ts
deployment/bin/setupEnvironment.ts

Voi lennossa muuttaa omaan dev/testi lambdalle omat, parameter storessa asennuksen aikaiset arvot - EmailsTo voidaan muuttaa devissä ja testissä oletusarvoisesti siihen yhteispostilaatikkoon, kunhan saadaan

lisätty ympäristömuuttujat email hallintaa varten

---

src/components/button/WindowCloseButton.tsx
src/components/projekti/aloituskuulutus/AloituskuulutusTiedostot.tsx
src/font-awesome-init.js
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
src/styles/globals.css

listätty dialogeihin yläkulmaan sulkemisrasti, korjattu hyväksyntädialogiin viranomaisvastaanottajat

fix: aloituskuulutuksen hyvaksyntanayttojen korjauksia

---

backend/src/asiakirja/suunnittelunAloitus/suunnittelunAloitusPdf.ts
src/components/projekti/ProjektiLiittyvatSuunnitelmat.tsx
src/components/projekti/aloituskuulutus/AloituskuulutusLukunakyma.tsx
src/schemas/asiatunnus.ts
src/schemas/perustiedot.ts

* Poistettu projektityypin lisays pdf otsikkoon (HASSU-446)
* Poistettu ylimaaraiset pisteet aloituskuulutusnaytolta (HASSU-497)
* Lisattu pituusrajoitus liittyvan suunnitelman asiatunnuskenttaan, seka asiatunnusskeema jatkokehitysta varten (HASSU-523)

fix: bugikorjauksia sprintti 8

---

src/__tests__/Perusta.test.tsx
src/components/HassuSpinner.tsx
src/pages/yllapito/index.tsx
src/pages/yllapito/perusta/[oid].tsx
src/pages/yllapito/perusta/index.tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
src/pages/yllapito/projekti/[oid]/henkilot.tsx
src/pages/yllapito/projekti/[oid]/index.tsx

mitä tuolle perustasivun testille pitäisi tehdä ja eikö se ole turha, koska robot testit

feat: spinner (HASSU-234)

---

src/components/form/Autocomplete.tsx
src/components/projekti/KayttoOikeusHallinta.tsx
src/pages/yllapito/projekti/[oid]/henkilot.tsx

Projektin henkilot sivu näyttämään toast tallennuksen yhteydessä, ja henkilöhaun autocomplete kenttä juttelemaan vasta tarvittaessa

fix: bugikorjauksia osa 2 (sprintti 8)

---

src/components/projekti/ProjektiPageLayout.tsx
src/pages/yllapito/projekti/[oid]/index.tsx

feat: Add update project button

feat: Add update project button

---

backend/src/handler/projektiAdapter.ts
src/components/projekti/suunnitteluvaihe/SuunniteluvaiheenVuorovaikuttaminen.tsx

* ei sisalla sahkopostinlahetysta, siita oma backend tiketti

feat: varmistusdialogi ja julkaisu (HASSU-588)

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/src/database/model/suunnitteluVaihe.ts
backend/src/handler/projektiAdapter.ts
backend/src/handler/projektiAdapterJulkinen.ts
graphql/inputs.graphql
graphql/types.graphql
src/components/projekti/suunnitteluvaihe/LuonnoksetJaAineistot.tsx
src/components/projekti/suunnitteluvaihe/SuunnitteluvaiheenPerustiedot.tsx
src/components/projekti/suunnitteluvaihe/SuunnitteluvaiheenVuorovaikuttaminen.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutustilaisuusDialog.tsx
src/pages/yllapito/projekti/[oid]/suunnittelu.tsx
src/schemas/vuorovaikutus.ts

feat: videolinkkien lisäämisen mahdollisuus

feat: videolinkkien lisäämisen mahdollisuus

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/integrationtest/api/api.test.ts
backend/src/aineisto/aineistoImporterLambda.ts
backend/src/aineisto/aineistoService.ts
backend/src/asiakirja/asiakirjaService.ts
backend/src/asiakirja/suunnittelunAloitus/Kutsu20.ts
backend/src/asiakirja/suunnittelunAloitus/kutsuPdf.ts
backend/src/database/projektiDatabase.ts
backend/src/email/email.ts
backend/src/files/fileService.ts
backend/src/handler/projektiHandler.ts
backend/src/vuorovaikutus/vuorovaikutusService.ts
backend/test/asiakirja/asiakirjaService.test.ts

* vuorovaikutuksen julkaisemisen tunnistaminen ja pdf:n generointi
* refaktorointia

feat: kutsu-pdf:n generointi vuorovaikutuksen julkaisemisen yhteydessä

---

src/hooks/useProjektiBreadcrumbs.tsx
src/locales/fi/common.json
src/locales/sv/common.json
src/pages/404.tsx
src/pages/suunnitelma/[oid]/aloituskuulutus.tsx
src/pages/suunnitelma/[oid]/suunnittelu.tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
src/pages/yllapito/projekti/[oid]/arkistoi.tsx
src/pages/yllapito/projekti/[oid]/index.tsx
src/pages/yllapito/projekti/[oid]/nahtavillaolo.tsx
src/pages/yllapito/projekti/[oid]/suunnittelu.tsx

fix: Make all pages use breadcrumbs properly when necessary
feat: Add custom 404 page to avoid error in breadcrumbs

fix: Make all pages use breadcrumbs properly when necessary

---

src/__tests__/VideoParser.test.tsx
src/__tests__/__snapshots__/VideoParser.test.tsx.snap
src/locales/fi/projekti.json
src/locales/sv/projekti.json
src/pages/suunnitelma/[oid]/suunnittelu.tsx
src/util/videoParser.ts

velhoaineisto omana tikettinään

feat: video ja muut materiaalit kansalaiselle (HASSU-599)

---

backend/src/asiakirja/suunnittelunAloitus/KutsuAdapter.ts
backend/src/handler/asiakirjaHandler.ts
deployment/lib/hassu-backend.ts
package.json
src/components/projekti/suunnitteluvaihe/SuunnitteluvaiheenVuorovaikuttaminen.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutustilaisuusDialog.tsx
src/pages/api/projekti/[oid]/suunnittelu/kutsu/pdf.ts
src/schemas/vuorovaikutus.ts

odottaa Mikon paluuta, jotta voidaan käydä taustapalvelun asiat yhdessä läpi

feat: vuorovaikuttamisen esikatselu (HASSU-587)

---

src/components/projekti/ProjektiLiittyvatSuunnitelmat.tsx
src/pages/yllapito/projekti/[oid]/index.tsx

usefieldarray append kun valitaan projektille liittyvan suunnitelmia

fix: liittyvat suunnitelmat korjaus

---

src/components/projekti/suunnitteluvaihe/VuorovaikutustilaisuusDialog.tsx

Refaktoroi Vuorovaikutuksen nimi ja aika omaksi elementiksi. Sen seurauksena bugi tuntuu korjaantuvan?

fix: Korjaa vuorovaikutustilaisuuden nimi -kentän fokus

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/integrationtest/api/api.test.ts
backend/integrationtest/api/testUtil/cleanUpFunctions.ts
backend/integrationtest/api/testUtil/tests.ts
backend/src/aineisto/aineistoImporterLambda.ts
backend/src/database/model/suunnitteluVaihe.ts
backend/src/handler/projektiAdapter.ts
backend/src/handler/projektiAdapterJulkinen.ts
graphql/inputs.graphql
graphql/types.graphql
src/components/HassuAccordion.tsx
src/components/button/ButtonFlat.tsx
src/components/projekti/suunnitteluvaihe/AineistojenValitseminenDialog.tsx
src/components/projekti/suunnitteluvaihe/IlmoituksenVastaanottajat.tsx
src/components/projekti/suunnitteluvaihe/LuonnoksetJaAineistot.tsx
src/components/projekti/suunnitteluvaihe/SuunnitteluvaiheenVuorovaikuttaminen.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikuttamisenInfo.tsx
src/pages/suunnitelma/[oid]/suunnittelu.tsx
src/schemas/vuorovaikutus.ts

Hei. Ihmettelin tässä kauan noita testien snapshotteja ja kuinka ne näyttäisi olevan pielessä. _Api should search, load and save a project 6_ tulos ei oikee näytä hyvältä. Outouksia on myös seuraavissakin testisnapshoteissa. En tiedä mistä johtuu.

feat: Vuorovaikutuksen aineistojen kategorisoinnin lisääminen päälomakkeelle

---

src/locales/fi/common.json
src/locales/fi/projekti.json
src/locales/sv/common.json
src/locales/sv/projekti.json
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
src/pages/suunnitelma/[oid]/suunnittelu.tsx

* lisatty yhteystiedoille kieliversion monikkotuki, nahtavillaolon pitka teksti parametrisoitu
* jos kaivataan tuki kaannoksiin upotettaville komponenteille tai html:lle, niin se omana tehtavanaan

feat: nahtavillaolovaiheen kansalaisnakyman tekstien rakenteiden muutoksia

---

src/components/projekti/kansalaisnakyma/ProjektiJulkinenPageLayout.tsx
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx

* array pop muutettu, velho tiedot muutettu hakemaan projektilta

fix: nahtavillaolo kansalaisnakyman ja kansalaisnakyman perussivun korjauksia

---

deployment/lib/hassu-frontend.ts
package.json

nextjs-API-lambda ei saanut headereita ollenkaan. Lisäsin melko brutaalisti policyn, jotta headerit tulee.
Lisäsin myös skriptit nextjs-api-lambdan logien lukemiseen.

fix: Korjaa ilmoitustaulusyötteen tunnistautuminen

---

backend/src/apiHandler.ts
common/abstractApi.ts
graphql/inputs.graphql
graphql/operations.graphql
src/components/form/FormGroup.tsx
src/components/projekti/kansalaisnakyma/MuistutusLomakeDialogi.tsx
src/locales/fi/common.json
src/locales/fi/projekti.json
src/locales/sv/common.json
src/locales/sv/projekti.json
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
src/schemas/nahtavillaoloMuistutus.ts
src/services/api/fragmentTypes.json
src/util/dateUtils.ts

* UI:n lisäksi, vain API, ei BE-toiminnallisuutta -> tulee omalla tiketillä

feat: muistutusdialogi ja rajapinta (HASSU-781)

---

backend/src/handler/projektiAdapter.ts

fix: Ota huomioon, että nähtävilläolovaiheen aineistoja ei välttämättä syötetä

---

deployment/lib/hassu-pipeline.ts
package.json

* ota pois husky hookit kun releasessa pushataan versiotagi
* ota kaikki webhookit pois testin e2etest-pipelinestä

fix: korjaa test-pipeline

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/integrationtest/api/api.test.ts
backend/integrationtest/api/testUtil/hyvaksyntaVaihe.ts
backend/integrationtest/api/testUtil/nahtavillaolo.ts
backend/integrationtest/api/testUtil/tests.ts
backend/integrationtest/api/testUtil/util.ts
backend/src/aineisto/aineistoImporterLambda.ts
backend/src/files/ProjektiPath.ts
backend/src/handler/projektiAdapter.ts
backend/test/__snapshots__/apiHandler.test.ts.snap

feat: BE: hyväksymisvaiheen aineistot

BE: hyväksymisvaiheen aineistot

---

backend/src/apiHandler.ts
backend/src/database/model/nahtavillaoloVaihe.ts
backend/src/email/emailTemplates.ts
backend/src/handler/emailHandler.ts
backend/src/muistutus/muistutusAdapter.ts
backend/src/muistutus/muistutusEmailService.ts
backend/src/muistutus/muistutusHandler.ts
backend/src/util/emailUtil.ts
backend/test/fixture/projektiFixture.ts
backend/test/muistutus/muistutusHandler.test.ts

liitteen lähetystä ei ole testattu

feat: muistutuksen kasittely (HASSU-775)

---

src/components/notification/Notification.tsx
src/components/projekti/hyvaksyminen/aineistot/Lukunakyma.tsx
src/components/projekti/hyvaksyminen/kuulutuksenTiedot/KuulutuksessaEsitettavatYhteystiedot.tsx
src/components/projekti/hyvaksyminen/kuulutuksenTiedot/Lukunakyma.tsx
src/components/projekti/hyvaksyminen/kuulutuksenTiedot/MuutoksenHaku.tsx
src/components/projekti/hyvaksyminen/kuulutuksenTiedot/index.tsx
src/locales/fi/common.json
src/locales/sv/common.json
src/pages/yllapito/projekti/[oid]/hyvaksymispaatos.tsx
src/styles/notification/Notification.module.css

Hox: vaatii rebasetuksen kun aiemmat PR on mergetty

feat: hassu 910 hyvaksymispaatos lukutila

---

src/pages/_app.tsx

Automaattitestit menee nyt läpi, kun apista saatavaa dataa ei revalidoida automaattisesti.

fix: Korjaa automaattitestit muokkaamalla datojen hakuparametreja

---

src/components/ProjektiListaus.tsx
src/components/layout/header/kansalaisHeader.tsx
src/components/layout/header/virkamiesHeader.tsx
src/components/layout/navigation/HeaderNavigationItem.tsx
src/locales/sv/common.json
src/pages/suunnitelma/[oid]/aloituskuulutus.tsx

Koti-ikonin vaihtoa ei vielä tehty, ui-kuvien mukainen tulee vasta fontawesome 6:ssa, eli pitänee miettiä vaihtoehtoja tai lopullista tarvetta

feat: kansalaisen header (HASSU-38)

---

src/pages/api/test/[oid]/nahtavillaolomenneisyyteen.dev.ts
src/util/basicAuthentication.ts

* add validation for testapi calls

fix: HASSU-977-api-sivujen-autentikaatio

---

src/components/kansalaisenEtusivu/Hakutulokset.tsx
src/components/kansalaisenEtusivu/Sivutus.tsx
src/components/kansalaisenEtusivu/TyylitellytKomponentit.tsx
src/locales/fi/common.json
src/locales/sv/common.json
src/pages/index.tsx

Pohjautuu mun aiemmalle PR:lle, eli pitää rebasettaa ennen mergeä. Toimii BE:n kanssa. Pitäisi olla menemättä rikki, vaikka osoiteriville kirjoittaa höpöä.

feat: hassu 991 sivutus

---

next.config.js
package.json
src/components/layout/layout.tsx
src/components/notification/NotificationBar.tsx
src/components/projekti/nahtavillaolo/kuulutuksentiedot/Lukunakyma.tsx
src/font-awesome-init.js

* lisatty tiedoituspalkki kehitys- ja testiymparistoihin, lisatty nahtavillaolon lukutilaan painike menneisyyteen siirtoa varten

feat: HASSU-978-nahtavillaolon-siirtomenneisyyteen-painike

---

cypress/integration/2-perusta-projekti/9-hyvaksyntavaihe.spec.js
src/components/projekti/hyvaksyminen/aineistot/HyvaksymisPaatosVaihePainikkeet.tsx
src/components/projekti/hyvaksyminen/aineistot/Hyvaksymispaatos.tsx
src/components/projekti/hyvaksyminen/kuulutuksenTiedot/Painikkeet.tsx
src/pages/yllapito/projekti/[oid]/hyvaksymispaatos.tsx

* lisatty hyvaksymispaatosvaiheen testit, id-tunnisteita ja painikkeiden korjauksia

feat: hyvaksymispaatos-automaattitestit (HASSU-837) 

---

src/components/layout/layout.tsx

* change node_env to hassus own environment variable

fix: HASSU-978

---

deployment/lib/hassu-frontend.ts
src/pages/api/kuntalista.json.ts

Nämä olivat menneet rikki kun poistin pipeline-buildeista .env.local-tiedoston. Se oli hämäävä, koska tuli mukaan mielestäni hallitsemattomasti.

fix: korjaa kuntalista ja ilmoitustaulusyöte

---

src/components/projekti/nahtavillaolo/kuulutuksentiedot/Lukunakyma.tsx

* change node_env to hassu own environment

fix: korjaa siirramenneisyyteen-painike

---

src/components/projekti/kansalaisnakyma/ProjektiJulkinenPageLayout.tsx
src/components/projekti/kansalaisnakyma/ProjektiJulkinenStepper.tsx
src/locales/fi/projekti.json
src/locales/sv/projekti.json

*  poistettu lainvoima kansalaisen stepperista

feat: poista lainvoima kansalaisen stepperista (HASSU-1013)

---

cypress/integration/3-hae-projekteja/1-kansalaisen-haut.spec.js
src/components/kansalaisenEtusivu/Hakulomake.tsx
src/components/kansalaisenEtusivu/Hakutulokset.tsx
src/components/kansalaisenEtusivu/Sivutus.tsx

npm run cypress run -- --spec "cypress/integration/3-hae-projekteja/*.spec.js"
olettaen, että automaattitestit on joskus ajettu läpi ja kannasta löytyy "hassu automaattitestiprojekti1"

feat: HASSU-1049 kansalaisen etusivun automaattitestit

---

next.config.js

* poimi devissa versiotieto codebuildin source version muuttujatsta (commit id)

fix: HASSU-1052 versiotiedot

---

src/components/kansalaisenEtusivu/Hakutulokset.tsx
src/components/kansalaisenEtusivu/TyylitellytKomponentit.tsx
src/locales/fi/projekti.json
src/locales/sv/projekti.json
src/util/dateUtils.ts

Näytä kansalaisen projektilistauksessa projektikortilla "Vuorovaikutus"-tagi, jos projekti on suunnitteluvaiheessa, ja sillä on tulossa vuorovaikutus tai on meneillään vuorovaikutus. Korjaa samassa PR:ssä yksi väärä linkkiosoite.

feat: hassu 1015

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/integrationtest/api/records/HYVAKSYMISPAATOS_APPROVED.json
backend/integrationtest/api/records/NAHTAVILLAOLO.json
backend/integrationtest/api/testUtil/tests.ts
backend/src/database/model/projekti.ts
backend/src/projekti/adapter/projektiAdapterJulkinen.ts
backend/src/projekti/kayttoOikeudetManager.ts
backend/test/__snapshots__/apiHandler.test.ts.snap
backend/test/apiHandler.test.ts
backend/test/projekti/__snapshots__/kayttoOikeudetManager.test.ts.snap
backend/test/projekti/kayttoOikeudetManager.test.ts
graphql/inputs.graphql
graphql/types.graphql
src/schemas/kayttoOikeudet.ts

Lisäsin "yleinenYhteystieto"-booleanin projektin käyttäjiin. Sama kenttä palautetaan myöskin kansalaispuolella projektin käyttäjien mukana.

feature: BE: yleinen yhteystieto julkiselle puolelle

---

backend/src/projekti/adapter/projektiAdapterJulkinen.ts
backend/src/util/adaptStandardiYhteystiedot.ts

fix: Vuorovaikutuksen yhteystiedot voi olla määrittelemättä

---

src/components/kansalaisenEtusivu/Hakutulokset.tsx
src/locales/fi/common.json
src/locales/sv/common.json
src/pages/suunnitelma/[oid]/[...all].tsx
src/pages/suunnitelma/[oid]/index.tsx
src/pages/yllapito/perusta/index.tsx

* lisaa projektin juurisivulle ja catch all -sivulle ohjaus aktiiviseen vaiheeseen

feat: HASSU-710 projektin reititys aktiiviseen vaiheeseen

---

backend/integrationtest/aloitusKuulutus/__snapshots__/aloitusKuulutusHandler.test.ts.snap
backend/src/asiakirja/suunnittelunAloitus/KutsuAdapter.ts
backend/src/email/emailTemplates.ts
backend/src/projektiSearch/projektiSearchAdapter.ts
backend/src/velho/velhoAdapter.ts
backend/src/velho/velhoClient.ts
backend/test/asiakirja/__snapshots__/asiakirjaService.test.ts.snap
backend/test/database/__snapshots__/projektiDatabase.test.ts.snap
backend/test/email/emailHandler.test.ts
backend/test/email/emailTemplate.test.ts
backend/test/fixture/projektiFixture.ts
backend/test/projekti/__snapshots__/projektiHandler.test.ts.snap
backend/test/projektiSearch/__snapshots__/dynamoDBStreamHandler.test.ts.snap
graphql/types.graphql
src/components/projekti/ProjektiKortti.tsx
src/components/projekti/ProjektiPerustiedot.tsx
src/components/projekti/kansalaisnakyma/MuistutusLomakeDialogi.tsx
src/pages/yllapito/index.tsx
src/pages/yllapito/perusta/index.tsx
src/util/getAsiatunnus.ts

* asiatunnuksen käsittely siten, että se on aina suunnittelusta vastaavan viranomaisen

feat: HASSU-131 asiatunnus

---

cypress/integration/2-perusta-projekti/99-imoitustaulusyote.spec.js
cypress/plugins/index.js
package.json

Lisätty chromeen käynnistysparametri, jolla selain pysyy desktop-moodissa, jotta datepicker-elementti sallii päivämäärän täyttämisen näppäimistöltä.

fix: korjaa cypress-testien ajaminen

---

src/pages/yllapito/projekti/[oid]/nahtavillaolo.tsx
src/pages/yllapito/projekti/[oid]/suunnittelu.tsx

Cypress-testit välillä failaa, kun tabit unmounttaantuu kesken testin. En saanut toistettua testien epäonnistumista ennen muutoksia enkä saa muutosten jälkeenkään. Joka tapauksessa nämä muutokset on hyvä lisätä.

fix: lisää memoizointia suunnittelu ja nahtavillaolovaiheisiin

---

src/pages/yllapito/projekti/[oid]/kasittelyntila.tsx
src/schemas/kasittelynTila.ts

Jos päätöksen päivämäärä on annettu, asiatunnus pitäisi olla pakollinen
Jos asiatunnus on annettu, päätöksen päivämäärä pitäisi olla pakollinen
Ensimmäisen hyväksymispäätöksen pvm aina pakollinen

fix: HASSU-1181 kasittelyn tilan pakollisuudet

---

src/components/projekti/kansalaisnakyma/ProjektiJulkinenStepper.tsx
src/locales/fi/projekti.json
src/locales/sv/projekti.json

Testihaaraan menossa pieniä tyylifiksejä ja tekstifiksejä. Alla ennen ja jälkeen kuvat.
**Ennen korjauksia**
**Korjausten jälkeen**

fix: Korjaa stepperin tyylejä ja tekstejä

---

backend/src/velho/velhoAdapter.ts
src/components/form/HassuDatePicker.tsx
src/components/kansalaisenEtusivu/Sivutus.tsx
src/components/layout/ScrollToTopButton.tsx
src/components/layout/footer.tsx
src/components/projekti/nahtavillaolo/kuulutuksentiedot/KuulutuksessaEsitettavatYhteystiedot.tsx
src/components/projekti/nahtavillaolo/kuulutuksentiedot/KuulutusJaJulkaisuPaiva.tsx
src/components/projekti/paatos/kuulutuksenTiedot/MuutoksenHaku.tsx
src/components/projekti/paatos/kuulutuksenTiedot/Voimassaolovuosi.tsx
src/services/api/commonApi.ts

Pääosin yhden rivin muutoksia, tyhjien tai käyttämättömien objektien poistoja
https://sonarqube.vaylapilvi.fi/project/issues?id=Hassu-main&resolved=false&types=BUG
Toiminnot joiden koodiin mm. koskettu:
- Velhosta tulevat kuntatiedot
- Päivämäärävalitsimet
- Kansalaisen etusivun sivutus
- Sivun ylös scrollaus-painike
- Footer
- Päätöksen kuulutuksen voimassaolovuosi-pudotusvalikko
- API-/Backend-virheiden välitys fronttiin

fix: HASSU-1221 small bugs reported by SonarQube

---

src/components/form/FileInput.tsx
src/components/layout/HassuMuiThemeProvider.tsx
src/components/layout/header/VirkamiesHeaderTopRightContent.tsx
src/components/layout/header/header.tsx
src/components/layout/navigation/HeaderNavigationItem.tsx
src/components/projekti/KayttoOikeusHallinta.tsx
src/components/projekti/ProjektiLiittyvatSuunnitelmat.tsx
src/components/projekti/ProjektiSunnittelusopimusTiedot.tsx
src/components/projekti/lukutila/ProjektinTiedotLukutila.tsx
src/locales/fi/projekti.json
src/locales/sv/projekti.json
src/pages/yllapito/projekti/[oid]/henkilot.tsx

Parannettu saavutettavuutta. Commit messageissa selostettu mitä ja miksi

fix: Korjaa käyttöliittymän yksityiskohtia

---

Dockerfile
common/BaseConfig.js
deployment/bin/createKeyForSignedCookies.sh
deployment/bin/updateCertificate.sh
deployment/lib/buildspec/buildspec-prod.yml
deployment/lib/buildspec/buildspec-training.yml
deployment/lib/buildspec/buildspec.yml
deployment/lib/hassu-pipelines.ts
deployment/package-lock.json
deployment/package.json
release.config.js

myös: hakuindeksien päivitys asennuksen jälkeen

feat: koulutusympäristön viimeistely. Sertifikaatin päivitystyökalu.

---

src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/LausuntopyyntoonLiitettavaLisaaineisto.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/Muokkausnakyma.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/NahtavillaoloPainikkeet.tsx

oikeastaan fix, mutta haluan, että build+testit ajetaan

feat: korjaa nähtävilläolovaiheen aineistolomake

---

cypress/integration/2-perusta-projekti/006-suunnitteluvaihe-perustiedot.spec.js
cypress/integration/2-perusta-projekti/008-nahtavillaolovaihe-perustiedot.spec.js
src/components/projekti/aloituskuulutus/KuulutuksenYhteystiedot.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/LausuntopyyntoonLiitettavaLisaaineisto.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/Muokkausnakyma.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/NahtavillaoloPainikkeet.tsx

Lisäksi poistettu aloituskuulutusvaiheessa löytynyt 'as'-tyyppipakotus

feat: Korjaa nähtävilläolovaiheen aineistojen tallennus

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/integrationtest/api/records/HYVAKSYMISPAATOS_APPROVED.json
backend/integrationtest/api/records/JATKOPAATOS_1_ALKU.json
backend/integrationtest/api/records/NAHTAVILLAOLO.json
backend/integrationtest/api/testUtil/tests.ts
backend/integrationtest/migraatio/__snapshots__/migration.test.ts.snap
backend/src/handler/tila/vuorovaikutusKierrosTilaManager.ts
backend/src/projekti/adapter/adaptToDB/adaptVuorovaikutusKierrosToSave.ts
backend/src/projekti/adapter/adaptToDB/common.ts
backend/test/projekti/projektiAdapter.test.ts
package.json
src/components/projekti/suunnitteluvaihe/LukutilaVuorovaikutukselle/LukutilaLinkkiJaKutsut.tsx
src/components/projekti/suunnitteluvaihe/LuonnoksetJaAineistot/EiJulkinen.tsx
src/components/projekti/suunnitteluvaihe/LuonnoksetJaAineistot/MuokkaustilainenLomake.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/SuunnittelunEteneminenJaArvioKestosta.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/index.tsx
src/components/projekti/suunnitteluvaihe/SuunnitteluvaihePageLayout.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/EsitettavatYhteystiedot.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/IlmoituksenVastaanottajat.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/index.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutusMahdollisuudet.tsx
src/pages/yllapito/projekti/[oid]/suunnittelu/vuorovaikuttaminen/index.tsx
src/schemas/suunnittelunPerustiedot.ts

Korjauksia suunnitteluvaiheeseen. Pääosin UI-korjauksia, mutta myös suunnitteluvaiheen Arvio seuraavan vaiheen alkamisesta -kentän tekeminen ei-pakolliseksi, ja korjaus adapterilogiikkaan siten, että on mahdollista nullata suunnitteluvaiheen kenttiä. Lisäsin myös yhden testin adapterille, joka saa kiinni sen bugin, joka oli ennen kyseistä adapterimuutosta.

feat: hassu 1358

---

common/kuntametadata.ts
src/components/form/FormGroup.tsx
src/components/form/HassuMuiSelect.tsx
src/components/form/Select.tsx
src/components/kansalaisenEtusivu/Hakulomake.tsx
src/pages/index.tsx

https://www.sketch.com/s/2a56e864-0b55-4ade-b294-17366a9a8a0e/a/jgYG077

feat: HASSU-1409 kansalaisen pudotusvalikot saavutettavuus

---

src/pages/yllapito/projekti/[oid]/index.tsx

Piilota vähäinen menettely, koska toiminnallisuutta ei ole vielä toteutettu

fix: Piilota vähäinen menettely

---

src/components/SideNavigation.tsx
src/components/button/JataPalautettaNappi.tsx
src/components/kansalainen/tietoaPalvelusta/AnnaPalvelustaPalautettaDialog.tsx
src/components/kansalainen/tietoaPalvelusta/StyledRating.tsx
src/components/layout/HassuMuiThemeProvider.tsx
src/components/layout/footer.tsx
src/font-awesome-init.js
src/locales/fi/footer.json
src/locales/sv/footer.json
src/locales/sv/tietoa-palvelusta/saavutettavuus.json
src/locales/sv/tietoa-palvelusta/tietoa-palvelusta.json
src/locales/sv/tietoa-palvelusta/tietoa-suunnittelusta.json
src/locales/sv/tietoa-palvelusta/yhteystiedot-ja-palaute.json

Footeriin
- Sosiaalisen median linkkien lisääminen
- Poistettu turhia linkkejä 
- Päivitetty linkkien ulkoasua 
- Lisätty oikeat hreffit linkkeihin 
Tietoa palvelusta sivuihin
- ulkoiset linkit kielivalinnan mukaan 
- palaute painikkeen alapuolista marginia korjattu 
- palatelomakkeen tyylejä korjattu 
- SideNavigation-komponentin key attribuuttien arvot muokattu array indeksin sijaan route.id:eitä 
- Mobiilia varten dialogiin erityylinen arvosanavalitsin (laitoin extrapaddingia sliderin ympärille, koska en onnistunut saamaan samaan aikaan vertikaalisesti scrollattavaa dialogia, jossa horisontaalisesti sisältö overflowaisi dialogin paddingin päälle)
Menossa hotfixina testiin

feat: Sosiaalisen median linkit footeriin ja sisällön päivitys

---

i18n.js
src/components/kansalainen/tietoaPalvelusta/AnnaPalvelustaPalautettaDialog.tsx
src/components/kansalainen/tietoaPalvelusta/StyledRating.tsx
src/components/layout/header/KansalaisHeaderTopRightContent.tsx
src/components/layout/header/header.tsx
src/components/layout/navigation/HeaderNavigationItem.tsx
src/locales/fi/header.json
src/locales/fi/tietoa-palvelusta/palautetta-palvelusta-dialog.json
src/locales/sv/footer.json
src/locales/sv/header.json
src/locales/sv/tietoa-palvelusta/palautetta-palvelusta-dialog.json
src/locales/sv/tietoa-palvelusta/yhteystiedot-ja-palaute.json

- Lisää headeriin anna palautetta nappi
- Korjattu footerista käännösongelma
- Muokattu kielikäännöspainikkeiden tyylejä
- Pieniä korjauksia headerin välityksiin

feat: Lisää anna palautetta nappi headeriin

---

src/components/projekti/nahtavillaolo/kuulutuksentiedot/Painikkeet.tsx
src/components/projekti/paatos/kuulutuksenTiedot/Painikkeet.tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx

* trigger validation on accept, add clickhandlers to all annoucements

fix: HASSU-1368 kuulutuksen hyväksyminen, kun kuulutuspäivä menneisyydessä

---

src/components/KeyValueTable.tsx
src/components/projekti/kansalaisnakyma/ProjektiJulkinenPageLayout.tsx
src/components/projekti/kansalaisnakyma/ProjektiJulkinenStepper.tsx
src/pages/suunnitelma/[oid]/aloituskuulutus.tsx

keyvaluetable julkisen puolen tyylit, aloituskuulutussivun asettelu, stepperin marginaali

feat: HASSU-1521 kansalaispuolen aloituskuulutus saavutettavuus ja design

---

src/components/kansalaisenEtusivu/Hakulomake.tsx
src/components/kansalaisenEtusivu/Hakutulokset.tsx
src/components/kansalaisenEtusivu/TyylitellytKomponentit.tsx
src/components/layout/SearchSection.tsx
src/pages/index.tsx

* otsikkohierarkiat, asettelut ja ulkoasu designin mukaiseksi

feat: HASSU-1520 kansalaisen etusivun saavutettavuus

---

src/components/button/JataPalautettaNappi.tsx
src/components/layout/Section.tsx
src/locales/fi/projekti.json
src/locales/fi/suunnittelu.json
src/locales/sv/projekti.json
src/locales/sv/suunnittelu.json
src/pages/suunnitelma/[oid]/suunnittelu.tsx
src/styles/globals.css

feat: HASSU-1522 suunnitteluvaihe saavutettavuus

---

backend/src/asiakirja/adapter/commonKutsuAdapter.ts
backend/src/asiakirja/suunnittelunAloitus/Kuulutus61.ts
backend/test/asiakirja/__snapshots__/asiakirjaService.test.ts.snap

Kielioppisyistä piti tehdä jotain muutoksia kääntämislogiikkaan

feat: korjaa kaantamislogiikkaa

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/src/handler/tila/vuorovaikutusKierrosTilaManager.ts

* lisaa vuorovaikutuskutsun posteihin cc, paivita snapit

feat: HASSU-1553 vuorovaikutusvaiheen kutsupostien cc:t

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/src/asiakirja/adapter/commonKutsuAdapter.ts
backend/src/asiakirja/adapter/hyvaksymisPaatosVaiheKutsuAdapter.ts
backend/src/email/emailTemplates.ts
backend/src/handler/asiakirjaAdapter.ts
backend/src/handler/emailHandler.ts
backend/src/handler/tila/hyvaksymisPaatosVaiheTilaManager.ts

Vahvaa copypastea. Halusin saada mahdollisimman pian toimivaa toteutettua.

feat: Lisää ilmoitusviestit hyväksymispäätökselle (laatijalle, projektipäällikölle ja viranomaisille)

---

src/components/projekti/common/KansalaisenAineistoNakyma.tsx
src/components/projekti/kansalaisnakyma/MuistutusLomakeDialogi.tsx
src/locales/fi/common.json
src/locales/fi/projekti.json
src/locales/sv/common.json
src/locales/sv/projekti.json
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
src/pages/suunnitelma/[oid]/suunnittelu.tsx

otsikot, valit, infolaatikot ok, kansalaisen aineistonakyman saavutettavuus puuttuu -> oma tiketti

feat: HASSU-1523 kansalaisen nahtavilläolo saavutettavuus ja design

---

backend/src/config.ts
backend/src/email/email.ts
deployment/lib/setupEnvironment.ts

* muutettu emailien lahettajan osoite ymparistomuuttujiin
* fallback osoite ilman hassu-sanaa @vaylapilvi.fi -domainista, josta sallittu kaikki (väyläpilven keskitetty ses-palvelu)

feat: HASSU-1551 noreply-osoite

---

src/components/ExtLink.tsx
src/components/projekti/common/KansalaisenAineistoNakyma.tsx
src/components/projekti/kansalaisnakyma/HyvaksymispaatosTiedot.tsx
src/locales/fi/projekti.json
src/locales/sv/projekti.json
src/pages/suunnitelma/[oid]/aloituskuulutus.tsx
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx

Kuulutusteksteistä puuttuu mm. päivämäärän boldaus, sekä on sisällöltään hieman erilainen kuin kuvassa - mutta muistaakseni nämä tekstit ovat juuri käyneet ison remontin pdf-tulostusta varten, joten varovasti oletin, että tekstit ovat oikein. 
Jos eivät ole, niin pitää varmistaa, että käytetään täsmälleen samoja tekstejä pdf:ssä ja html-muotoilut eivät valu sinne.
~~branchatty #646~~

feat: HASSU-1524 kansalaisen hyvaksymisvaihe saavutettavuus

---

common/kaannettavatKielet.ts

Aattelin että tuollainen tyyppi ja funkkari voisi olla. Tuota voi sit käyttää BE:ssä ja FE:ssä. Tein tämän erillisenä, kun tehdään BE ja FE rinnakkain.

feat: käännettavat kielet -tyyppi ja apufunkkari commoniin

---

src/pages/tietoa-palvelusta/yhteystiedot-ja-palaute.tsx

* otsikot alemmaksi hierarkiassa

fix: HASSU-1519 palautesivujen otsikkohierarkia

---

backend/integrationtest/api/records/HYVAKSYMISPAATOS_APPROVED.json
backend/integrationtest/api/records/JATKOPAATOS_1_ALKU.json
backend/integrationtest/api/records/NAHTAVILLAOLO.json
backend/src/handler/emailHandler.ts
backend/src/handler/tila/vuorovaikutusKierrosTilaManager.ts

Toivon katselmoijan kliksuttelevan tämän UI:ssa läpi. Mietityttää myös, onko ongelma, kun tuolla on toi saveProjektiWithoutLocking ton vuorovaikutuskierrosjulkaisu-saven kanssa. Savettavat kyllä eri asioita toki (vuorovaikutusKierros vs. vuorovaikutusKierrosJulkaisu).

feat: HASSUYP-12 HASSU-1622

---

src/components/projekti/kansalaisnakyma/ProjektiJulkinenPageLayout.tsx
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx

Harmaa laatikko nähtävilläoloon, joka näyttää linkin saame-pdf:ään. Saamenkieliset tekstit. Projektin nimi saameksi. Kielitagi. Teksti ruudunlukijalle.
https://www.sketch.com/s/190d5682-3ede-4988-99c0-d26c0ae16073/a/x0b2DK5
https://www.sketch.com/s/190d5682-3ede-4988-99c0-d26c0ae16073/a/uuid/98D164F3-9569-415A-A9EE-85B1C74E6960

feat: HASSU-1610 nähtävilläolo saame public

---

src/components/projekti/kansalaisnakyma/PaatosPageLayout.tsx
src/pages/suunnitelma/[oid]/aloituskuulutus.tsx
src/pages/suunnitelma/[oid]/hyvaksymismenettelyssa.tsx
src/pages/suunnitelma/[oid]/hyvaksymispaatos.tsx
src/pages/suunnitelma/[oid]/jatkopaatos1.tsx
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
src/pages/suunnitelma/[oid]/suunnittelu.tsx

hassu 1356 hassu 1609 hassu 1611 hassu 1612
https://www.sketch.com/s/190d5682-3ede-4988-99c0-d26c0ae16073/a/x0b2DK5
https://www.sketch.com/s/190d5682-3ede-4988-99c0-d26c0ae16073/a/uuid/98D164F3-9569-415A-A9EE-85B1C74E6960
Tässä tiketissä saamenkieliset käännökset liitteenä:
https://extranet.vayla.fi/jira/browse/HASSU-1334

feat: loput kansalaispuolen saame-FE-hommat

---

backend/src/projektiSearch/projektiSearchAdapter.ts
backend/test/projektiSearch/__snapshots__/dynamoDBStreamHandler.test.ts.snap
graphql/types.graphql
src/components/kansalaisenEtusivu/Hakutulokset.tsx
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx

Indeksointiin otetaan mukaan tieto saamenkielisyydestä, ja kansalaisen projektilistauksessa näytetään saamenlippu, jos projektin toinen kieli on saame.

feat: hassu 1664 saamenlippu listaukseen

---

src/components/projekti/kansalaisnakyma/MuistutusLomakeDialogi.tsx
src/components/projekti/kansalaisnakyma/PalauteLomakeDialogi.tsx
src/locales/fi/projekti.json
src/locales/sv/projekti.json
src/pages/suunnitelma/[oid]/suunnittelu.tsx

* lisaa tietosuojateksti, funktiot oikean linkin valitsemiselle (kts. tiketti), kaannokset

feat: HASSU-1597 tietosuojatekstit muistutus ja palautelomakkeisiin

---

src/components/kansalaisenEtusivu/TyylitellytKomponentit.tsx
src/pages/index.tsx

* rivita hakutulosten otsikot, saamewidget gridiin ja responsiiviseksi

fix: HASSUYP-62 saamenkielinen sivupalkki

---

src/schemas/kasittelynTila.ts

* poista hyvaksymispaatostietojen pakollisuus, jata vaihtoehtoinen pakolisuus

fix: HASSUYP-29 kasittelyn tila

---

backend/src/projektiSearch/projektiSearchService.ts

* korjaa epaaktiivset haku muuttamalla projektityypin oletusarvo

fix: HASSUYP-52

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/integrationtest/api/api.test.ts
backend/integrationtest/api/apiTestFixture.ts
backend/integrationtest/api/records/HYVAKSYMISPAATOS_APPROVED.json
backend/integrationtest/api/records/JATKOPAATOS_1_ALKU.json
backend/integrationtest/api/records/NAHTAVILLAOLO.json
backend/integrationtest/api/testUtil/tests.ts
backend/integrationtest/migraatio/__snapshots__/migration.test.ts.snap
backend/integrationtest/migraatio/migration.test.ts
backend/src/files/ProjektiPath.ts
backend/src/migraatio/migration.ts
backend/src/projekti/projektiHandler.ts
backend/src/projekti/projektiValidator.ts
backend/test/files/__snapshots__/projektiPaths.test.ts.snap
backend/test/fixture/projektiFixture.ts
backend/test/handler/tila/nahtavillaoloTilaManager.test.ts
src/components/projekti/suunnitteluvaihe/PageLayout/AiemmatVuorovaikutuksetOsio/index.tsx
src/components/projekti/suunnitteluvaihe/PageLayout/index.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/index.tsx

Jatkossa vuorovaikutuskierrosnumerot alkaa aina 1:stä ja aineistoken polussa on vuorovaikutuksen tietokantanumeroa vastaava numero. Korjattu kaikki mahdollinen aiheeseen liittyen tässä PR:ssä (toivottavasti).

feat: hassu 1729 id 1

---

backend/src/projektiSearch/projekti-mapping.json
backend/src/projektiSearch/projektiSearchAdapter.ts
backend/src/projektiSearch/projektiSearchService.ts
backend/test/projektiSearch/__snapshots__/dynamoDBStreamHandler.test.ts.snap
backend/test/projektiSearch/__snapshots__/projektiSearchService.test.ts.snap
backend/test/projektiSearch/projektiSearchService.test.ts
graphql/types.graphql
src/components/HassuTable.tsx
src/components/projekti/ProjektiSideNavigation.tsx
src/components/virkamies/etusivu/RiittamattomatOikeudetDialog.tsx
src/hooks/useHassuTable.tsx
src/pages/yllapito/index.tsx
src/services/api/fragmentTypes.json

Lisäksi myös uudelleenohjaus projektisivuilta, mikäli käyttäjällä ei ole oikeuksia.

feat: HASSU-1158 Lisää Riittämättömät oikeudet -dialogi virkamiehen etusivulle, mikä näytetään, jos käyttäjältä puuttuu oikeudet valittuun projektiin

---

backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/integrationtest/api/api.test.ts
backend/integrationtest/api/testUtil/tests.ts
backend/src/handler/tila/vuorovaikutusKierrosTilaManager.ts
backend/src/util/adaptStandardiYhteystiedot.ts
backend/test/handler/tila/vuorovaikutusKierrosTilaManager.test.ts
src/components/projekti/suunnitteluvaihe/KierroksenPoistoDialogi.tsx
src/components/projekti/suunnitteluvaihe/PageLayout/AiemmatVuorovaikutuksetOsio/index.tsx
src/components/projekti/suunnitteluvaihe/PageLayout/index.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/index.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/index.tsx

vuorovaikutuskierroksen poistaminen ja validointi siihen liittyen. Testejä myös tehty.

feat: hassu 1725 nähtävilläolon poisto ja indikaattorit aiempien kierrosten tilasta

---

backend/integrationtest/aloitusKuulutus/__snapshots__/aloitusKuulutusHandler.test.ts.snap
backend/integrationtest/api/__snapshots__/api.test.ts.snap
backend/src/asiakirja/adapter/nahtavillaoloVaiheKutsuAdapter.ts
backend/src/email/emailTemplates.ts
backend/src/email/lahetekirje/lahetekirjeEmailTemplate.ts
backend/test/email/__snapshots__/emailHandler.test.ts.snap
src/locales/sv/projekti.json

* lisaa yhteystiedot sahkopostiin, korjaa sahkopostien ruotsinnokset ja nahtavillaolon yllapito url

fix: HASSUYP-24 nähtävilläolon sähköpostit

---

src/components/projekti/kansalaisnakyma/SaameContent.tsx
src/pages/suunnitelma/[oid]/aloituskuulutus.tsx
src/pages/suunnitelma/[oid]/hyvaksymispaatos.tsx
src/pages/suunnitelma/[oid]/jatkopaatos1.tsx
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx
src/pages/suunnitelma/[oid]/suunnittelu.tsx

- Katso, että kaikissa vaiheissa on litteenä saamenkielinen kutsu tai kuulutus (pl. Hyväksymismenettelyssä).
- Katso, että body-teksti on aina 16 px.
- Katso, että linkkitekstit on aina 16 px.
- Katso, että linkkitekstit ovat boldattu

feat: HASSU-1722 saamenkieliset infot

---

src/components/layout/footer.tsx
src/locales/fi/footer.json
src/locales/sv/footer.json

Ruotsiksi ja suomeksi pitäisi tulla nyt fiksut tekstit ruudunlukijalle/alt-teksteiksi

feat: Tee some-alt-teksteistä speksin mukaiset

---

src/components/button/JataPalautettaNappi.tsx
src/locales/sv/projekti.json
src/pages/suunnitelma/[oid]/nahtavillaolo.tsx

* lisaa kansalaisen muistutusinfo

feat: HASSUYP-91 muistutusinfo

---

src/components/projekti/ProjektiEuRahoitusTiedot.tsx
src/components/projekti/ProjektiSunnittelusopimusTiedot.tsx
src/pages/yllapito/projekti/[oid]/index.tsx

* vaihda i-infot harmaiksi, vain ohjelaatikot sinisella

fix: HASSUYP-120 infolaatikot harmaiksi

---

src/components/projekti/common/SuunnitelmatJaAineistot.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/LausuntopyyntoonLiitettavaLisaaineisto.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/Muokkausnakyma.tsx

En ymmärrä miksi toi useFieldArrayn replace toimii tossa kohtaa ja useFormin setValue ei. Ei ymmärrä.

fix: HASSU-1818 Aseta lisäaineistot näkymään ensimmäisen lisäyksen yhteydessä

---

src/components/projekti/Ajansiirto.tsx
src/components/projekti/ProjektiSideNavigation.tsx
src/font-awesome-init.js

Projektin sivulla virkamiespuolella on nyt vasemmassa palkissa yleinen ajansiirtotoiminto-UI

feat: yleinen ajansiirto fe

---

src/pages/yllapito/projekti/[oid]/index.tsx

delete operaattori ei onnistunut poistamaan suunnittelusopimuksen lokalisoituja logoja

fix: Korjaa lokalisoitujen suunnittelusopimuslogojen tallennus

---

src/components/form/HassuMuiSelect.tsx

* rajoita valikon max korkeus n. 20 valinnalle

feat: HASSUYP-121 pudotusvalikon käytettävyys

---

src/components/kansalaisenEtusivu/Hakulomake.tsx
src/components/layout/header/header.tsx
src/components/projekti/kansalaisnakyma/ProjektiJulkinenPageLayout.tsx
src/locales/fi/header.json
src/locales/sv/header.json
src/pages/tietoa-palvelusta/diehtu-planemis.tsx
src/pages/tietoa-palvelusta/index.tsx
src/pages/tietoa-palvelusta/saavutettavuus.tsx
src/pages/tietoa-palvelusta/tietoa-suunnittelusta.tsx
src/pages/tietoa-palvelusta/yhteystiedot-ja-palaute.tsx
src/styles/globals.css

* lisaa painike ja kaannokset julkiselle puolelle

feat: HASSUYP-92 hyppaa sisaltoon

---

src/pages/yllapito/perusta/[oid].tsx

* kovakoodaus pois takaisin -painikkeesta

feat: HASSUYP-140 projektin perustaminen ja peruminen

---

backend/src/projekti/adapter/haeAktiivisenVaiheenAsianhallinanTila.ts
backend/src/util/isProjektiAsianhallintaIntegrationEnabled.ts
backend/test/__snapshots__/apiHandler.test.ts.snap
common/util/haeVaiheidentiedot.ts
common/util/operationValidators.ts

Projektin statuksen perusteella ei voinutkaan oikeen hakea minkä vaiheen tilaa haetaan, koska status vaihtuu jo kun vaihe on viety hyväksyttäväksi.

fix: HASSU-1842 Korjaa minkä vaiheen asianhallinnan tila haetaan, kun kuulutus on hyväksynnässä

---

backend/src/tiedostot/ProjektiTiedostoManager/VaiheTiedostoManager.ts
backend/src/util/localization.ts

* lisaa kaannospalveluun aineistot ja kayta zipeissa

fix: zip aineistopolkujen korjaus

---

backend/src/database/model/projekti.ts
backend/src/projekti/validator/validateKasittelyntila.ts
backend/src/velho/velhoAdapter.ts
backend/test/projekti/validator/projektiValidator/validateKasittelyntila.test.ts

Samalla korjattu aktiivinen flägin aiheuttama ongelma käsittelytilan validoinnissa.

fix: HASSUYP-231: Liikenteelle luovutuksen päivämäärä ei ole siirtynyt Velhoon

---

src/components/projekti/SelitteetUudelleenkuulutukselle.tsx
src/components/projekti/aloituskuulutus/AloituskuulutusLukunakyma.tsx
src/components/projekti/aloituskuulutus/AloituskuulutusTiedostot.tsx
src/components/projekti/lukutila/SuunnitteluvaiheenPerustiedotLukutila.tsx
src/components/projekti/lukutila/UudelleenKuulutusSelitteetLukutila.tsx
src/components/projekti/nahtavillaolo/kuulutuksentiedot/HankkeenSisallonKuvaus.tsx
src/components/projekti/nahtavillaolo/kuulutuksentiedot/KuulutuksenJaIlmoituksenEsikatselu.tsx
src/components/projekti/nahtavillaolo/kuulutuksentiedot/Lukunakyma.tsx
src/components/projekti/paatos/kuulutuksenTiedot/KuulutuksenJaIlmoituksenEsikatselu.tsx
src/components/projekti/paatos/kuulutuksenTiedot/Lukunakyma.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/EnnaltaKuvattuVideoesittely.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/MuuEsittelymateriaali.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/SuunnittelunEteneminenJaArvioKestosta.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/HankkeenSisallonKuvaus.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/index.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutusPaivamaaraJaTiedotLukutila.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/Lisatiedot.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/Soittoaika.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/TilaisuudenNimiJaAika.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/Verkkotilaisuus.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/Yleisotilaisuus.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/index.tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
src/util/textUtil.ts

Asiakkaan raportoima ongelma on johtunut siitä, että mun tekemän mokan takia lomakkeen labelit on olleet väärin päin, ja asiakas on syöttänyt ruotsinkielisen sisällön suomenkielisen sisällön inputtiin ja päinvastoin.

feat: Korjaa label-funktio ja muuta sen käyttökohdat korjauksen mukaisesti.

---

backend/src/database/model/suunnitteluVaihe.ts
backend/src/handler/asiakirjaAdapter.ts
backend/src/handler/tila/KuulutusTilaManager.ts
backend/src/handler/tila/TilaManager.ts
backend/src/handler/tila/nahtavillaoloTilaManager.ts
backend/src/handler/tila/vuorovaikutusKierrosTilaManager.ts
backend/src/projekti/adapter/haeAktiivisenVaiheenAsianhallinanTila.ts
backend/src/tiedostot/ProjektiTiedostoManager/VuorovaikutusKierrosTiedostoManager.ts
common/util/haeVaiheidentiedot.ts
graphql/types.graphql
migration-cli/package-lock.json
package-lock.json
package.json
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/index.tsx
src/pages/yllapito/projekti/[oid]/index.tsx

Huomio. Tämä ohjattu menemään test -haaraan

feat: HASSU-1874 ASHA - Palaaminen nähtävilläolovaiheesta suunnitteluvaiheeseen

---

backend/src/asianhallinta/asianhallintaService.ts
backend/src/projekti/projektiUtil.ts
common/isVaylaAsianhallinta.ts
src/components/projekti/HyvaksyJaPalautaPainikkeet.tsx
src/components/projekti/KuulutuksenHyvaksyminenDialog.tsx
src/components/projekti/common/OhjelistaNotification.tsx
src/components/projekti/nahtavillaolo/NahtavillaoloPageLayout.tsx
src/components/projekti/paatos/PaatosPageLayout.tsx
src/components/projekti/suunnitteluvaihe/PageLayout/index.tsx
src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx

Tiketillä olevat emailien muutokset tulee erikseen. Ei laitettu tähän, koska niissä on vielä työtä ja konfliktoisi muihin emaili muutoksiin, jotka on tekeillä.

fix: HASSU-1867 Päivitä asianhallintoihin liittyviä ohjeistuksia

---

deployment/bin/setupEnvironment.ts
deployment/lib/hassu-frontend.ts
deployment/lib/setupEnvironment.ts
next.config.js
src/components/layout/header/KansalaisHeaderTopRightContent.tsx
src/components/layout/header/SuomiFiLogin.tsx
src/locales/fi/common.json
src/locales/sv/common.json
src/services/userService.ts

* set keycloak logout urls and add logout button

feat: HASSU-226 uloskirjautuminen keycloakista

---

deployment/bin/setupEnvironment.ts
deployment/lib/hassu-frontend.ts
deployment/lib/setupEnvironment.ts
next.config.js
src/components/layout/header/SuomiFiLogin.tsx
src/pages/api/slo.ts
src/services/userService.ts

* move keycloak logout redirect to api

fix: keycloak uloskirjautumisen siirto apin taakse

---

backend/src/asianhallinta/asianhallintaService.ts
backend/src/handler/tila/hyvaksymisPaatosVaiheTilaManager.ts
backend/src/handler/tila/nahtavillaoloTilaManager.ts
backend/src/muistutus/muistutusHandler.ts
backend/src/tiedostot/ProjektiTiedostoManager/HyvaksymisPaatosVaiheTiedostoManager.ts
backend/src/tiedostot/ProjektiTiedostoManager/NahtavillaoloVaiheTiedostoManager.ts
migration-cli/package-lock.json
package-lock.json
package.json
src/services/api/fragmentTypes.json

feat: HASSU-1922: Lisätieto asianhallintaan, jos asianosaisia ei ole tiedotettu

---

backend/integrationtest/HyvaksymisEsitys/suljeMuokkaus.test.ts
backend/src/HyvaksymisEsitys/actions/suljeMuokkaus.ts
backend/src/HyvaksymisEsitys/actions/tallennaJaLahetaHyvaksyttavaksi.ts
backend/src/user/userService.ts

feat: testit hyväksymisesityksen muokkauksen sulkuun

---

backend/integrationtest/HyvaksymisEsitys/listaaTiedostot.test.ts
backend/src/HyvaksymisEsitys/latauslinkit/createLadattavatTiedostot.ts
backend/src/files/fileService.ts
backend/src/tiedostot/adaptToLadattavaTiedosto/adaptAineistoNew.ts
backend/src/tiedostot/adaptToLadattavaTiedosto/adaptKunnallinenLadattuTiedosto.ts
backend/src/tiedostot/adaptToLadattavaTiedosto/adaptLadattuTiedostoNew.ts
backend/src/tiedostot/adaptToLadattavaTiedosto/util.ts

Testataan, että listaaTiedostot antaa toimivat latauslinkit. Tässä yhteydessä korjauksia koodiin, jotta se oikeasti toimisi...

feat: hassuyp 393 hyv es listaa tiedostot muu pt1

---

src/components/projekti/common/StyledMap.tsx
src/map/control/ReadFeaturesFromGeoJsonFileInputControl.tsx

fix: HASSU-1954: Geojson-tiedoston tuonti aiheuttaa virheilmoituksen

---

backend/integrationtest/HyvaksymisEsitys/TEST_HYVAKSYMISESITYS_INPUT.ts
backend/src/HyvaksymisEsitys/adaptToSave/adaptHyvaksymisEsitysToSave.ts
graphql/inputs.graphql
src/components/HyvaksymisEsitys/getDefaultValuesForForm.ts

Muutoksen myötä lomakkeen tekeminen FE:ssä on paljon helpompaa, koska voi käyttä useFieldArray eikä tarvi transformoida dataa.

feat: Hyv es vastaanottajat input on objekti array, ei string array

---

backend/integrationtest/HyvaksymisEsitys/avaaMuokkaus.test.ts
backend/integrationtest/HyvaksymisEsitys/esikatseleTiedostot.test.ts
backend/integrationtest/HyvaksymisEsitys/hylkaa.test.ts
backend/integrationtest/HyvaksymisEsitys/hyvaksy.test.ts
backend/integrationtest/HyvaksymisEsitys/listaaTiedostot.test.ts
backend/integrationtest/HyvaksymisEsitys/suljeMuokkaus.test.ts
backend/integrationtest/HyvaksymisEsitys/tallenna.test.ts
backend/integrationtest/HyvaksymisEsitys/tallennaJaLahetaHyvaksyttavaksi.test.ts
backend/integrationtest/HyvaksymisEsitys/util.ts
backend/integrationtest/user/haeKayttoOikeudet.test.ts
backend/integrationtest/util/databaseUtil.ts
backend/src/api/yllapitoOperations.ts
backend/src/projekti/adapter/adaptToAPI/common/adaptDBVaylaUserToAPI.ts
backend/src/projekti/adapter/adaptToAPI/common/index.ts
backend/src/projekti/adapter/projektiAdapter.ts
backend/src/projekti/kayttoOikeudetManager.ts
backend/src/user/haeKayttoOikeudet.ts
backend/test/fixture/userFixture.ts
common/ProjektiValidationContext.ts
common/abstractApi.ts
common/util/userRights.ts
graphql/operations.graphql
graphql/types.graphql
src/components/HyvaksymisEsitys/HyvaksymisEsitysLukutila.tsx
src/hooks/useKayttoOikeudet.tsx
src/hooks/useProjekti.tsx
src/pages/yllapito/projekti/[oid]/hyvaksymisesitys.tsx
src/services/api/fragmentTypes.json
src/util/userRights.ts

Hox: testien apufunktioita on siirretty ylemmälle tasolle. Siitä tulee paljon muutoksia tiedostoihin.

feat: hae kayttooikeudet erikseen

---

backend/integrationtest/HyvaksymisEsitys/haeTiedot.test.ts
backend/src/HyvaksymisEsitys/actions/haeTiedot.ts
backend/src/HyvaksymisEsitys/dynamoDBCalls/getHyvaksymisEsityksenTiedot.ts
graphql/types.graphql
i18n.js
src/components/HassuAccordion.tsx
src/components/HyvaksymisEsitys/HyvaksymisEsitysLukutila.tsx
src/components/NestedAineistoAccordion.tsx
src/components/projekti/common/Aineistot/AineistoTable/AineistoAlakategoria.tsx
src/components/projekti/common/KansalaisenAineistoNakyma.tsx
src/components/projekti/nahtavillaolo/nahtavilleAsetettavatAineistot/NahtavillaolonAineistoLomake.tsx
src/components/projekti/paatos/aineistot/MuokkausNakyma/AineistoLomake.tsx
src/components/projekti/suunnitteluvaihe/Perustiedot/SuunnitelmaLuonnoksetJaEsittelyAineistot.tsx.tsx
src/components/tiedosto.tsx
src/services/api/fragmentTypes.json

Lukutilan pitäisi olla nyt kunnossa muotoiluineen. Hyväksymisen odottamisessa pitäisi näkyä oikeat infolootat riippuen katsooko sivua projektihenkilö vai projari/admin. Hyväksytyssä lukutilassa pitäisi olla myös oikea infoloota.
Suunnitelmankin pitäisi näkyä oikein. Testatessa voi vaikka kopioida suunnitelman nähtävilläolosta. Muistaa vaan ottaa "tila"- ja "tiedosto"-kentät pois ja laittaa "tuotu"-aikaleiman nimeksi "lisatty". Sitä, että aineistojen linkit toimii, ei voi vielä testata, koska aineistot eivät lataudu, mutta linkkien muodon pitäisi olla FE:n linkeissä oikein.

feat: hassuyp 403 lukutila

---

backend/integrationtest/HyvaksymisEsitys/esikatseleTiedostot.test.ts
src/components/HyvaksymisEsitys/LomakeComponents/Laskutustiedot.tsx

fix: HASSUYP-402-korjaus korjaa näytettävä asiatunnus

---

backend/integrationtest/HyvaksymisEsitys/__snapshots__/hyvaksy.test.ts.snap
backend/integrationtest/HyvaksymisEsitys/__snapshots__/tallennaJaLahetaHyvaksyttavaksi.test.ts.snap
backend/integrationtest/HyvaksymisEsitys/hyvaksy.test.ts
backend/integrationtest/HyvaksymisEsitys/tallennaJaLahetaHyvaksyttavaksi.test.ts
backend/src/HyvaksymisEsitys/actions/hyvaksy.ts
backend/src/HyvaksymisEsitys/actions/tallennaJaLahetaHyvaksyttavaksi.ts
backend/src/HyvaksymisEsitys/dynamoKutsut.ts
backend/src/asianhallinta/getLinkkiAsianhallintaan.ts
backend/src/email/emailTemplates.ts
backend/src/util/isProjektiAsianhallintaIntegrationEnabled.ts
common/isVaylaAsianhallinta.ts

Sähköpostien pitäisi lähteä nyt speksien mukaan. Liitteet kans. Testit myös tehty aiheesta.

feat: hassuyp 321 hyv es email

---

src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/HyvaksymisDialogi.tsx
src/components/projekti/suunnitteluvaihe/VuorovaikutusKierros/index.tsx

Jira-tiketti: [HASSUYP-253](https://extranet.vayla.fi/jira/browse/HASSUYP-253)

Fix: HASSUYP-253 lisätty integraatio-ohjeistus suunnitteluvaiheen dialogiin

---

migration-cli/package-lock.json
package-lock.json
package.json

Vähän hakuammuntaa, mutta tällä versionostolla voisi olla vaikutusta tuohon ongelmaan.

fix: HASSUYP-332 - Korjaa aineistotaulukosta johtuva "application error" ongelma

---

src/pages/suunnitelma/[oid]/suunnittelu.tsx

tiketti: [HASSUYP-436](https://extranet.vayla.fi/jira/browse/HASSUYP-436)

fix: shrinked iframe to half its size in mobile

---

src/components/projekti/kansalaisnakyma/ProjektiJulkinenStepper.tsx
src/locales/fi/projekti.json
src/locales/sv/projekti.json

tiketti: [HASSUYP-136](https://extranet.vayla.fi/jira/browse/HASSUYP-136)

fix: hassuyp 149 kansalaisen mobiili stepperin viimeistely

---

src/components/Tagi.tsx
src/components/button/ButtonFlat.tsx
src/components/layout/HassuMuiThemeProvider.tsx
src/components/notification/Notification.tsx
src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/index.tsx
src/components/projekti/tiedottaminen/TiedotettavaHaitari.tsx
src/pages/suunnitelma/[oid]/suunnittelu.tsx
src/svg/ViivaIkoni.tsx

Iconeissa en huomannut vääriä värejä, mutta lisäsin värejä väripalettiin ja korjasin parin elementin tyyliä väripaletin mukaiseksi.

fix: HASSUYP-90 Lisää värejä väripalettiin ja korjaa löydettyjä väripoikkeamia

---

backend/src/asianhallinta/getLinkkiAsianhallintaan.ts
backend/src/aws/lambda.ts
backend/src/cache/s3Cache.ts
backend/src/endDateCalculator/bankHolidaysClient.ts
backend/src/personSearch/personSearchClient.ts
backend/src/personSearch/personSearchUpdaterClient.ts
backend/src/projekti/adapter/projektiAdapter.ts
backend/src/velho/velhoClient.ts
src/components/projekti/perusosio/ProjektinLinkit.tsx

Säädin tuota invokeLambdaa ettei saisi niitä InvalidSignatureException: Signature expired virheitä. Tosin mitään takuita ei oo että korjaus mitään tekee.

feat: HASSUYP-243: Linkki ASHA:an/USPAn (Projektin tiedot)

---

backend/src/archive/projektiArchiveService.ts
backend/src/database/model/projekti.ts
backend/src/database/muistuttajaDatabase.ts
backend/src/database/omistajaDatabase.ts
backend/src/velho/velhoAdapter.ts
graphql/inputs.graphql
graphql/types.graphql
src/components/projekti/lukutila/KasittelynTilaLukutila.tsx
src/pages/yllapito/projekti/[oid]/arkistoi.dev.tsx
src/pages/yllapito/projekti/[oid]/kasittelyntila.tsx
src/schemas/kasittelynTila.ts

Korjasin myös arkistoinnin tuplakutsut ui:sta sekä muistuttajien ja omistajien poistot batch operaatiosta transaktioksi koska ne batch operaatiot saattaa throtlaa.

HASSUYP-124: Käsittelyn tila: yleissuunnitelmaan liittyvät kentät

---

backend/src/velho/velhoClient.ts

Laitoin baseksi test-haaran, jotta voidaan viedä 0.31.0:seen

fix: HASSUYP-534 Älä hae geometriatietoja Velho-projektin päivittämisen yhteydessä

---

backend/src/velho/hakupalvelu/api.ts
backend/src/velho/projektirekisteri/api.ts

Ohjattu tuotantohaaraan. Tarkoitus viedä muihin haaroihin mergeämällä tuotantohaara.

chore: HASSUYP-541 Päivitä Projektivelhon rajapintatyypitys tuotantorajapinnan tasaiseksi

---

i18n.js
src/components/projekti/kansalaisnakyma/PalauteKyselyMuistutusPopup.tsx
src/components/projekti/kansalaisnakyma/ProjektiJulkinenPageLayout.tsx
src/locales/fi/palautekyselymuistutus.json
src/locales/sv/palautekyselymuistutus.json
src/pages/index.tsx
src/util/haePalauteKyselyTiedot.tsx

Lisätty puuttunut pop-up palautekyselylle.

feat: HASSUYP-517 - Lisätty pop-up palautekyselylle

---

src/pages/yllapito/projekti/[oid]/tiedottaminen/kiinteistonomistajat/index.tsx
src/pages/yllapito/projekti/[oid]/tiedottaminen/kiinteistonomistajat/muokkaa.tsx

Pieni sananmuutos kiinteistönomistajanäkymään.

feat: HASSUYP-543 - Kiinteistönomistajanäkymään sanamuutos

---

entrypoint.sh

Reverts finnishtransportagency/hassu#1412

Revert "fix: HASSUYP-514: Korvattavat ympäristömuuttujat ovat string arvoja"

---

src/components/projekti/ProjektiSideNavigation.tsx
src/components/projekti/nahtavillaolo/kuulutuksentiedot/Lukunakyma.tsx
src/components/projekti/paatos/kuulutuksenTiedot/Lukunakyma.tsx
src/components/projekti/suunnitteluvaihe/LukutilaVuorovaikutukselle/index.tsx

* Tallennetaan funktion tulos muuttujaan, jolloin build timen optimointi ei heitä koko komponenttia mäkeen muuttujan ollessa aina false buildin yhteydessä (Lopullinen arvo määrittyy ennen ajon alkua).
* Tekoälyn mukaan kun funktion tulos on muuttujassa optimoija ei pysty optimoimaan komponenttia pois, koska tuloksessa voi olla sivuvaikutuksia.

HASSUYP-514: koitetaan saada NEXT_PUBLIC_AJANSIIRTO_SALLITTU ympäristömuuttuja toimimaan 
